# Task 1

In [68]:
import pandas as pd

In [69]:
marks = pd.Series([78,85,90,66,72])

In [70]:
marks

0    78
1    85
2    90
3    66
4    72
dtype: int64

In [71]:
marks.value_counts()

78    1
85    1
90    1
66    1
72    1
Name: count, dtype: int64

In [72]:
marks.index

RangeIndex(start=0, stop=5, step=1)

In [73]:
marks.dtype

dtype('int64')

In [74]:
marks.head(1)

0    78
dtype: int64

In [75]:
marks.tail(2)

3    66
4    72
dtype: int64

# Task 2

In [76]:
marks

0    78
1    85
2    90
3    66
4    72
dtype: int64

In [77]:
marks=pd.Series(marks + 5)
marks

0    83
1    90
2    95
3    71
4    77
dtype: int64

In [78]:
marks - 2

0    81
1    88
2    93
3    69
4    75
dtype: int64

In [79]:
marks * 1.05

0    87.15
1    94.50
2    99.75
3    74.55
4    80.85
dtype: float64

In [80]:
marks / 2

0    41.5
1    45.0
2    47.5
3    35.5
4    38.5
dtype: float64

# Task 3

In [81]:
marks

0    83
1    90
2    95
3    71
4    77
dtype: int64

In [82]:
print(marks.max())

95

In [83]:
print(marks.min())

71

In [84]:
print(marks.sum())

416

In [85]:
print(marks.mean())

83.2

In [86]:
count = 0
for i in marks:
    if(i >= 70):
        count += 1
print(count)

5

# Task 4

In [87]:
students = pd.DataFrame({'Name' : ['Amit','Neha','Rahul','Sneha','Pooja'],
                         'Marks': [78,85,90,66,72],
                         'Subject': ['Math','Math','Science','Science','Math']})

In [88]:
students

    Name  Marks  Subject
0   Amit     78     Math
1   Neha     85     Math
2  Rahul     90  Science
3  Sneha     66  Science
4  Pooja     72     Math

In [89]:
students.head(3)

    Name  Marks  Subject
0   Amit     78     Math
1   Neha     85     Math
2  Rahul     90  Science

In [90]:
students.tail(2)

    Name  Marks  Subject
3  Sneha     66  Science
4  Pooja     72     Math

In [91]:
students.shape

(5, 3)

In [92]:
students.columns

Index(['Name', 'Marks', 'Subject'], dtype='str')

# Task 5

In [93]:
students.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     5 non-null      str
 1   Marks    5 non-null      int64
 2   Subject  5 non-null      str
dtypes: int64(1), str(2)
memory usage: 301.0 bytes

In [94]:
students.describe()

           Marks
count   5.000000
mean   78.200000
std     9.654015
min    66.000000
25%    72.000000
50%    78.000000
75%    85.000000
max    90.000000

In [95]:
students.head()

    Name  Marks  Subject
0   Amit     78     Math
1   Neha     85     Math
2  Rahul     90  Science
3  Sneha     66  Science
4  Pooja     72     Math

In [96]:
students.tail()

    Name  Marks  Subject
0   Amit     78     Math
1   Neha     85     Math
2  Rahul     90  Science
3  Sneha     66  Science
4  Pooja     72     Math

In [97]:
students

    Name  Marks  Subject
0   Amit     78     Math
1   Neha     85     Math
2  Rahul     90  Science
3  Sneha     66  Science
4  Pooja     72     Math

In [122]:
students = students['Marks'].sort_values(ascending=False)

In [123]:
students

2    90
1    85
0    78
4    72
3    66
Name: Marks, dtype: int64

In [126]:
students=students.reset_index()

In [127]:
students

   index  Marks
0      2     90
1      1     85
2      0     78
3      4     72
4      3     66

# Task 6