# Automated Data Cleaning

#### Types of Missing Data :

#### 1. Missing Compleately at Random (MCAR)
#### 2. Missing At Random (MAR)
#### 3. Missing Not At Random (MNAR)

In [27]:
import pandas as pd

In [28]:
df = pd.read_csv('unclean_smartwatch_health_data.csv')

In [29]:
df.head()

,User ID,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
0,4174.0,58.939776,98.809650,5450.390578,7.167235622316564,Highly Active,1
1,NaN,NaN,98.532195,727.601610,6.538239375570314,Highly_Active,5
2,1860.0,247.803052,97.052954,2826.521994,ERROR,Highly Active,5
3,2294.0,40.000000,96.894213,13797.338044,7.367789630207228,Actve,3
4,2130.0,61.950165,98.583797,15679.067648,NaN,Highly_Active,6

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   User ID                 9799 non-null   float64
 1   Heart Rate (BPM)        9600 non-null   float64
 2   Blood Oxygen Level (%)  9700 non-null   float64
 3   Step Count              9900 non-null   float64
 4   Sleep Duration (hours)  9850 non-null   object
 5   Activity Level          9800 non-null   object
 6   Stress Level            9800 non-null   object
dtypes: float64(4), object(3)
memory usage: 547.0+ KB

In [31]:
df['User ID'].isnull().sum()

np.int64(201)

In [32]:
df = df.drop(columns=['User ID'])

In [33]:
df.isnull().sum()

Heart Rate (BPM)          400
Blood Oxygen Level (%)    300
Step Count                100
Sleep Duration (hours)    150
Activity Level            200
Stress Level              200
dtype: int64

In [34]:
df['Heart Rate (BPM)'].isnull().sum()

np.int64(400)

In [35]:
## 400 ---> 1,2,3 which one
df[df['Heart Rate (BPM)'].isnull()==True]

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
1,NaN,98.532195,727.601610,6.538239375570314,Highly_Active,5
17,NaN,96.052853,3488.919508,6.718661172525927,Seddentary,4
75,NaN,100.000000,3124.118038,4.229887888280923,Actve,1
105,NaN,98.276558,3039.112276,5.209658021888749,NaN,6
158,NaN,99.478461,11559.663606,6.470651489160172,Highly_Active,7
...,...,...,...,...,...,...
9875,NaN,99.842527,4454.770218,5.520745925308887,Sedentary,3
9956,NaN,100.000000,3584.236177,6.659533807452561,Highly_Active,5
9971,NaN,99.319841,26.215769,6.367659085134144,Active,10
9990,NaN,100.000000,3817.269018,8.595259517189332,Seddentary,2
9998,NaN,98.401058,3364.788855,5.691233932149209,Active,8

In [36]:
## drop missing data ----> dropna()

In [37]:
## Mean/Median Imputation ---> Fill the Missing Data with the Mean or Median of ALL rows of that column

In [38]:
## While gng with mean value ---> Check for the Outliers

## Age ---> 500(Outliers) ---> 10000 ---> mean ???

## Age ---> Median ---> If you will arrange all values from low to high side ---> Middle value

## Age ---> Mode ---> Most Frequent Age ---> Age

## 1,2,3,...50...100,500

In [39]:
df['Heart Rate (BPM)'].describe()

count    9600.000000
mean       76.035462
std        19.412483
min        40.000000
25%        64.890152
50%        75.220601
75%        85.198249
max       296.593970
Name: Heart Rate (BPM), dtype: float64

In [40]:
df['Heart Rate (BPM)'].median()

75.22060125775644

In [43]:
df['Heart Rate (BPM)']=df['Heart Rate (BPM)'].fillna(df['Heart Rate (BPM)'].median())

In [44]:
df['Heart Rate (BPM)'].isnull().sum()

np.int64(0)

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  9700 non-null   float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   object
 4   Activity Level          9800 non-null   object
 5   Stress Level            9800 non-null   object
dtypes: float64(3), object(3)
memory usage: 468.9+ KB

In [50]:
## Next Column
df['Blood Oxygen Level (%)'].isnull().sum()

np.int64(300)

In [47]:
df[df['Blood Oxygen Level (%)'].isnull()==True]

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
10,101.914938,NaN,2987.568640,7.541956463173237,Sedentary,9
21,68.310104,NaN,1058.374274,6.456918401449286,Actve,3
133,77.907578,NaN,15672.467752,9.079469571860296,Sedentary,10
134,78.227923,NaN,789.365922,3.5252990125882064,Seddentary,3
187,89.486636,NaN,2689.849911,5.737108446097524,Seddentary,6
...,...,...,...,...,...,...
9834,64.803112,NaN,1647.308449,8.04238137746177,Highly Active,7
9861,57.617790,NaN,14269.737149,6.390686112594759,Highly_Active,9
9885,75.281591,NaN,3852.160740,8.970316986352344,Actve,NaN
9905,87.693723,NaN,2364.028205,3.5490963940132865,Seddentary,3
9979,58.797407,NaN,359.210435,8.035879532058063,Active,5

In [49]:
## We Should figure out are there any outliers or not
df.describe()

       Heart Rate (BPM)  Blood Oxygen Level (%)    Step Count
count      10000.000000             9700.000000   9900.000000
mean          76.002867               97.841581   6985.685885
std           19.020902                1.732863   6885.809680
min           40.000000               90.791208      0.910138
25%           65.322796               96.662683   2021.039657
50%           75.220601               98.010642   4962.534599
75%           84.791711               99.376179   9724.902880
max          296.593970              100.000000  62486.690753

In [51]:
## No Outliers
df['Blood Oxygen Level (%)']=df['Blood Oxygen Level (%)'].fillna(df['Blood Oxygen Level (%)'].mean())

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   object
 4   Activity Level          9800 non-null   object
 5   Stress Level            9800 non-null   object
dtypes: float64(3), object(3)
memory usage: 468.9+ KB

In [56]:
### Forward Filling or Backward filling ---> Part of Time Series Data

### Forward Filling --->
5
6
7
9
10

### Backward filling
5
6
8
8
9

9

In [59]:
df.isnull().sum()

Heart Rate (BPM)            0
Blood Oxygen Level (%)      0
Step Count                  0
Sleep Duration (hours)    150
Activity Level            200
Stress Level              200
dtype: int64

In [55]:
df[df['Step Count'].isnull() == True]

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
136,70.593014,97.473981,NaN,3.439287691081752,Highly_Active,6
204,75.220601,98.710637,NaN,5.756958709255954,Highly_Active,8
603,69.084103,99.627473,NaN,6.358184719715759,Highly_Active,7
716,83.258294,98.704757,NaN,5.486240700986009,Seddentary,3
739,97.506420,97.651407,NaN,7.465981460156365,Active,6
...,...,...,...,...,...,...
9097,62.072133,96.810967,NaN,5.828570383973958,Seddentary,6
9121,54.793814,99.670176,NaN,6.686430627866978,Seddentary,2
9191,101.777396,100.000000,NaN,8.07989468005159,Active,10
9527,75.220601,94.694312,NaN,4.186856483292383,Seddentary,4
9565,90.411615,95.009355,NaN,8.582820460042822,Sedentary,4

In [57]:
## Forward Filling
### method ----> ffill or bfill

df['Step Count']=df['Step Count'].fillna(method='ffill')

C:\Users\ASUS\AppData\Local\Temp\ipykernel_27748\1947579252.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Step Count']=df['Step Count'].fillna(method='ffill')

In [58]:
df['Step Count'].isnull().sum()

np.int64(0)

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              10000 non-null  float64
 3   Sleep Duration (hours)  9850 non-null   object
 4   Activity Level          9800 non-null   object
 5   Stress Level            9800 non-null   object
dtypes: float64(3), object(3)
memory usage: 468.9+ KB

In [61]:
df['Sleep Duration (hours)'].dtype

dtype('O')

In [63]:
## not completly objects but some values are of object but other float
df.head()

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
0,58.939776,98.809650,5450.390578,7.167235622316564,Highly Active,1
1,75.220601,98.532195,727.601610,6.538239375570314,Highly_Active,5
2,247.803052,97.052954,2826.521994,ERROR,Highly Active,5
3,40.000000,96.894213,13797.338044,7.367789630207228,Actve,3
4,61.950165,98.583797,15679.067648,NaN,Highly_Active,6

In [ ]:
df[df['Sleep Duration (hours)'] == "ERROR"].shape
## 247 rows 😯

(247, 6)

In [70]:
## should we remove all rows of errors NO
## ERROR values to missing values

## First Object dtype ---> Numeric ---> pandas we use
## the function is to_numeric() in pandas library

In [71]:
df['Sleep Duration (hours)'] = pd.to_numeric(df['Sleep Duration (hours)'])

ValueError: Unable to parse string "ERROR" at position 2

In [72]:
df['Sleep Duration (hours)'] = pd.to_numeric(df['Sleep Duration (hours)'],errors = 'coerce')

In [73]:
## ERRORS ---> NaN values 😊

In [75]:
df[df['Sleep Duration (hours)']=='ERROR']
## No Errors😁

Empty DataFrame
Columns: [Heart Rate (BPM), Blood Oxygen Level (%), Step Count, Sleep Duration (hours), Activity Level, Stress Level]
Index: []

In [76]:
df['Sleep Duration (hours)'].dtype

dtype('float64')

In [80]:
df['Sleep Duration (hours)'].mean()

np.float64(6.505462918406444)

In [81]:
df['Sleep Duration (hours)'].median()

6.503308362112644

In [82]:
df['Sleep Duration (hours)'] = df['Sleep Duration (hours)'].fillna(df['Sleep Duration (hours)'].mean())

In [84]:
df['Sleep Duration (hours)'].isnull().sum()

np.int64(0)

In [85]:
df.head()

,Heart Rate (BPM),Blood Oxygen Level (%),Step Count,Sleep Duration (hours),Activity Level,Stress Level
0,58.939776,98.809650,5450.390578,7.167236,Highly Active,1
1,75.220601,98.532195,727.601610,6.538239,Highly_Active,5
2,247.803052,97.052954,2826.521994,6.505463,Highly Active,5
3,40.000000,96.894213,13797.338044,7.367790,Actve,3
4,61.950165,98.583797,15679.067648,6.505463,Highly_Active,6

In [87]:
## For Categorical Columns ---> Mode Frequently Repeating value in your column

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              10000 non-null  float64
 3   Sleep Duration (hours)  10000 non-null  float64
 4   Activity Level          9800 non-null   object
 5   Stress Level            9800 non-null   object
dtypes: float64(4), object(2)
memory usage: 468.9+ KB

In [90]:
## Next Column
df['Activity Level'].isnull().sum()

np.int64(200)

In [91]:
df['Activity Level'].mode()

0    Seddentary
Name: Activity Level, dtype: object

In [92]:
df['Activity Level'] = df['Activity Level'].fillna('Seddentary')

In [93]:
df['Activity Level']

0       Highly Active
1       Highly_Active
2       Highly Active
3               Actve
4       Highly_Active
            ...
9995           Active
9996        Sedentary
9997        Sedentary
9998           Active
9999            Actve
Name: Activity Level, Length: 10000, dtype: object

In [94]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              10000 non-null  float64
 3   Sleep Duration (hours)  10000 non-null  float64
 4   Activity Level          10000 non-null  object
 5   Stress Level            9800 non-null   object
dtypes: float64(4), object(2)
memory usage: 468.9+ KB

In [95]:
df['Stress Level'].isnull().sum()

np.int64(200)

In [96]:
## Constant Imputation ---> When you want to fill missing values with a constant value like 'unknown' or 0

In [100]:
df['Stress Level'].value_counts()

Stress Level
2            1007
7            1006
6            1001
3             995
1             984
9             976
4             966
10            954
5             945
8             917
Very High      49
Name: count, dtype: int64

In [102]:
df['Stress Level'] = df['Stress Level'].fillna(5)

In [103]:
df['Stress Level']

0       1
1       5
2       5
3       3
4       6
       ..
9995    7
9996    2
9997    4
9998    8
9999    5
Name: Stress Level, Length: 10000, dtype: object

In [104]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              10000 non-null  float64
 3   Sleep Duration (hours)  10000 non-null  float64
 4   Activity Level          10000 non-null  object
 5   Stress Level            10000 non-null  object
dtypes: float64(4), object(2)
memory usage: 468.9+ KB

### All missing values are replaced and fill


### this ia all manually but we can automate all these using simple imupter

In [140]:
### Automated Data Cleaning

In [108]:
df = pd.read_csv('unclean_smartwatch_health_data.csv')

In [109]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   User ID                 9799 non-null   float64
 1   Heart Rate (BPM)        9600 non-null   float64
 2   Blood Oxygen Level (%)  9700 non-null   float64
 3   Step Count              9900 non-null   float64
 4   Sleep Duration (hours)  9850 non-null   object
 5   Activity Level          9800 non-null   object
 6   Stress Level            9800 non-null   object
dtypes: float64(4), object(3)
memory usage: 547.0+ KB

In [111]:
df = df.drop(columns=['User ID'])

In [113]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        9600 non-null   float64
 1   Blood Oxygen Level (%)  9700 non-null   float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   object
 4   Activity Level          9800 non-null   object
 5   Stress Level            9800 non-null   object
dtypes: float64(3), object(3)
memory usage: 468.9+ KB

In [116]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy = 'median')

In [118]:
df['Heart Rate (BPM)'] = imputer.fit_transform(df['Heart Rate (BPM)'])

ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.

In [120]:
## double paranthesis and ravel() ---> function
df['Heart Rate (BPM)'] = imputer.fit_transform(df[['Heart Rate (BPM)']]).ravel()

In [121]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  9700 non-null   float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   object
 4   Activity Level          9800 non-null   object
 5   Stress Level            9800 non-null   object
dtypes: float64(3), object(3)
memory usage: 468.9+ KB

In [122]:
df.describe()

       Heart Rate (BPM)  Blood Oxygen Level (%)    Step Count
count      10000.000000             9700.000000   9900.000000
mean          76.002867               97.841581   6985.685885
std           19.020902                1.732863   6885.809680
min           40.000000               90.791208      0.910138
25%           65.322796               96.662683   2021.039657
50%           75.220601               98.010642   4962.534599
75%           84.791711               99.376179   9724.902880
max          296.593970              100.000000  62486.690753

In [123]:
imputer = SimpleImputer(strategy = 'mean')

In [124]:
df['Blood Oxygen Level (%)'] = imputer.fit_transform(df[['Blood Oxygen Level (%)']]).ravel()

In [125]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   object
 4   Activity Level          9800 non-null   object
 5   Stress Level            9800 non-null   object
dtypes: float64(3), object(3)
memory usage: 468.9+ KB

In [134]:
imputer = SimpleImputer(strategy='most_frequent')

In [135]:
df['Activity Level'] = imputer.fit_transform(df[['Activity Level']]).ravel()

In [136]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   object
 4   Activity Level          10000 non-null  object
 5   Stress Level            9800 non-null   object
dtypes: float64(3), object(3)
memory usage: 468.9+ KB

In [137]:
imputer = SimpleImputer(strategy='constant',fill_value=5)

In [138]:
df['Stress Level'] = imputer.fit_transform(df[['Stress Level']]).ravel()

In [139]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Heart Rate (BPM)        10000 non-null  float64
 1   Blood Oxygen Level (%)  10000 non-null  float64
 2   Step Count              9900 non-null   float64
 3   Sleep Duration (hours)  9850 non-null   object
 4   Activity Level          10000 non-null  object
 5   Stress Level            10000 non-null  object
dtypes: float64(3), object(3)
memory usage: 468.9+ KB