## Data Gathering Using the read_csv() ---> CSV file

### 1. How to read content from a csv files

In [1]:
import pandas as pd

In [7]:
titanic = pd.read_csv('Titanic-Dataset.csv')

In [8]:
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
pd.read_csv('katalog_gempa_v2.tsv')

C:\Users\ASUS\AppData\Local\Temp\ipykernel_24408\1086053737.py:1: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv('katalog_gempa_v2.tsv',sep='\t')

,eventID,datetime,latitude,longitude,magnitude,mag_type,depth,phasecount,azimuth_gap,location,...,doubleCouple,clvd,strikeNP1,dipNP1,rakeNP1,strikeNP2,dipNP2,rakeNP2,azgapFM,misfit
0,bmg2008vkye,2008-11-01 00:31:25.143741+00:00,-0.604440,98.895531,2.989742,MLv,20,6,146.707380,"Southern Sumatra, Indonesia",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,bmg2008vkzn,2008-11-01 01:13:15.738091+00:00,-3.386660,148.874180,5.208121,mb,51,38,190.275630,Bismarck Sea,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,bmg2008vlag,2008-11-01 01:34:29.660856+00:00,-6.611860,129.387220,5.507549,mb,30,62,45.467640,Banda Sea,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,bmg2008vlaj,2008-11-01 01:38:14.802129+00:00,-3.650586,127.990680,3.539674,MLv,5,4,331.974040,"Seram, Indonesia",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,bmg2008vlbt,2008-11-01 02:20:05.909515+00:00,-4.198925,128.097000,2.424314,MLv,5,5,326.379930,Banda Sea,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176379,bmg2026nsab,2026-07-14 20:26:41.769949+00:00,0.120709,122.167458,2.476112,M,180,13,107.618664,"Minahassa Peninsula, Sulawesi",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176380,bmg2026nsai,2026-07-14 20:34:15.492794+00:00,-2.743634,129.173599,3.256532,M,18,14,108.371223,"Seram, Indonesia",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176381,bmg2026nsba,2026-07-14 20:56:11.729362+00:00,1.759947,122.211578,4.238763,M,10,17,212.534500,"Minahassa Peninsula, Sulawesi",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176382,bmg2026nseu,2026-07-14 22:50:13.246583+00:00,-20.824007,-178.249603,7.334316,Mw,254,1,360.000000,Fiji Islands Region,...,0.999411,0.000589,270.176592,89.834714,172.557351,0.198184,82.557382,0.166691,360.0,0.082207
176383,bmg2026nsha,2026-07-14 23:58:03.041589+00:00,-2.614751,139.089417,4.662608,M,13,17,105.460907,Near North Coast of West Papua,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## read_csv() --- > 1. sep (seperation) --- > how values are seperated from each other in a given file

#### csv --- > amit,28 --- > sep=","
##### tsv -- > amit\t28 ---- > sep ="\t"

In [6]:
pd.read_csv('katalog_gempa_v2.tsv',sep='\t')

C:\Users\ASUS\AppData\Local\Temp\ipykernel_24408\1086053737.py:1: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv('katalog_gempa_v2.tsv',sep='\t')

,eventID,datetime,latitude,longitude,magnitude,mag_type,depth,phasecount,azimuth_gap,location,...,doubleCouple,clvd,strikeNP1,dipNP1,rakeNP1,strikeNP2,dipNP2,rakeNP2,azgapFM,misfit
0,bmg2008vkye,2008-11-01 00:31:25.143741+00:00,-0.604440,98.895531,2.989742,MLv,20,6,146.707380,"Southern Sumatra, Indonesia",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,bmg2008vkzn,2008-11-01 01:13:15.738091+00:00,-3.386660,148.874180,5.208121,mb,51,38,190.275630,Bismarck Sea,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,bmg2008vlag,2008-11-01 01:34:29.660856+00:00,-6.611860,129.387220,5.507549,mb,30,62,45.467640,Banda Sea,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,bmg2008vlaj,2008-11-01 01:38:14.802129+00:00,-3.650586,127.990680,3.539674,MLv,5,4,331.974040,"Seram, Indonesia",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,bmg2008vlbt,2008-11-01 02:20:05.909515+00:00,-4.198925,128.097000,2.424314,MLv,5,5,326.379930,Banda Sea,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176379,bmg2026nsab,2026-07-14 20:26:41.769949+00:00,0.120709,122.167458,2.476112,M,180,13,107.618664,"Minahassa Peninsula, Sulawesi",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176380,bmg2026nsai,2026-07-14 20:34:15.492794+00:00,-2.743634,129.173599,3.256532,M,18,14,108.371223,"Seram, Indonesia",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176381,bmg2026nsba,2026-07-14 20:56:11.729362+00:00,1.759947,122.211578,4.238763,M,10,17,212.534500,"Minahassa Peninsula, Sulawesi",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176382,bmg2026nseu,2026-07-14 22:50:13.246583+00:00,-20.824007,-178.249603,7.334316,Mw,254,1,360.000000,Fiji Islands Region,...,0.999411,0.000589,270.176592,89.834714,172.557351,0.198184,82.557382,0.166691,360.0,0.082207
176383,bmg2026nsha,2026-07-14 23:58:03.041589+00:00,-2.614751,139.089417,4.662608,M,13,17,105.460907,Near North Coast of West Papua,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### 2. names ---> names is going to take a list of names that we can provide to our column names

#### ----> names = ['Name','Age']

#### we can change the names

In [14]:
pd.read_csv('Titanic-Dataset.csv',names = ['P_ID','Survived','P_Class','P_Name','Gender','Age','Sibling or Spouse','Parch','Ticket_ID','Fare','Cabin','Starting Journey'])

,P_ID,Survived,P_Class,P_Name,Gender,Age,Sibling or Spouse,Parch,Ticket_ID,Fare,Cabin,Starting Journey
0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.25,NaN,S
2,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
3,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.925,NaN,S
4,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1,C123,S
...,...,...,...,...,...,...,...,...,...,...,...,...
887,887,0,2,"Montvila, Rev. Juozas",male,27,0,0,211536,13,NaN,S
888,888,1,1,"Graham, Miss. Margaret Edith",female,19,0,0,112053,30,B42,S
889,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
890,890,1,1,"Behr, Mr. Karl Howell",male,26,0,0,111369,30,C148,C
891,891,0,3,"Dooley, Mr. Patrick",male,32,0,0,370376,7.75,NaN,Q