## Data Gathering Using the read_csv() ---> CSV file

### 1. How to read content from a csv files

In [2]:
import pandas as pd

In [7]:
titanic = pd.read_csv('Titanic-Dataset.csv')

In [8]:
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
pd.read_csv('katalog_gempa_v2.tsv')

C:\Users\ASUS\AppData\Local\Temp\ipykernel_24408\1086053737.py:1: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv('katalog_gempa_v2.tsv',sep='\t')

,eventID,datetime,latitude,longitude,magnitude,mag_type,depth,phasecount,azimuth_gap,location,...,doubleCouple,clvd,strikeNP1,dipNP1,rakeNP1,strikeNP2,dipNP2,rakeNP2,azgapFM,misfit
0,bmg2008vkye,2008-11-01 00:31:25.143741+00:00,-0.604440,98.895531,2.989742,MLv,20,6,146.707380,"Southern Sumatra, Indonesia",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,bmg2008vkzn,2008-11-01 01:13:15.738091+00:00,-3.386660,148.874180,5.208121,mb,51,38,190.275630,Bismarck Sea,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,bmg2008vlag,2008-11-01 01:34:29.660856+00:00,-6.611860,129.387220,5.507549,mb,30,62,45.467640,Banda Sea,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,bmg2008vlaj,2008-11-01 01:38:14.802129+00:00,-3.650586,127.990680,3.539674,MLv,5,4,331.974040,"Seram, Indonesia",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,bmg2008vlbt,2008-11-01 02:20:05.909515+00:00,-4.198925,128.097000,2.424314,MLv,5,5,326.379930,Banda Sea,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176379,bmg2026nsab,2026-07-14 20:26:41.769949+00:00,0.120709,122.167458,2.476112,M,180,13,107.618664,"Minahassa Peninsula, Sulawesi",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176380,bmg2026nsai,2026-07-14 20:34:15.492794+00:00,-2.743634,129.173599,3.256532,M,18,14,108.371223,"Seram, Indonesia",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176381,bmg2026nsba,2026-07-14 20:56:11.729362+00:00,1.759947,122.211578,4.238763,M,10,17,212.534500,"Minahassa Peninsula, Sulawesi",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176382,bmg2026nseu,2026-07-14 22:50:13.246583+00:00,-20.824007,-178.249603,7.334316,Mw,254,1,360.000000,Fiji Islands Region,...,0.999411,0.000589,270.176592,89.834714,172.557351,0.198184,82.557382,0.166691,360.0,0.082207
176383,bmg2026nsha,2026-07-14 23:58:03.041589+00:00,-2.614751,139.089417,4.662608,M,13,17,105.460907,Near North Coast of West Papua,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## read_csv() --- > 1. sep (seperation) --- > how values are seperated from each other in a given file

#### csv --- > amit,28 --- > sep=","
##### tsv -- > amit\t28 ---- > sep ="\t"

In [16]:
tsv = pd.read_csv('katalog_gempa_v2.tsv',sep='\t')

C:\Users\ASUS\AppData\Local\Temp\ipykernel_1188\3088670335.py:1: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  tsv = pd.read_csv('katalog_gempa_v2.tsv',sep='\t')

In [17]:
tsv

,eventID,datetime,latitude,longitude,magnitude,mag_type,depth,phasecount,azimuth_gap,location,...,doubleCouple,clvd,strikeNP1,dipNP1,rakeNP1,strikeNP2,dipNP2,rakeNP2,azgapFM,misfit
0,bmg2008vkye,2008-11-01 00:31:25.143741+00:00,-0.604440,98.895531,2.989742,MLv,20,6,146.707380,"Southern Sumatra, Indonesia",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,bmg2008vkzn,2008-11-01 01:13:15.738091+00:00,-3.386660,148.874180,5.208121,mb,51,38,190.275630,Bismarck Sea,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,bmg2008vlag,2008-11-01 01:34:29.660856+00:00,-6.611860,129.387220,5.507549,mb,30,62,45.467640,Banda Sea,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,bmg2008vlaj,2008-11-01 01:38:14.802129+00:00,-3.650586,127.990680,3.539674,MLv,5,4,331.974040,"Seram, Indonesia",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,bmg2008vlbt,2008-11-01 02:20:05.909515+00:00,-4.198925,128.097000,2.424314,MLv,5,5,326.379930,Banda Sea,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176379,bmg2026nsab,2026-07-14 20:26:41.769949+00:00,0.120709,122.167458,2.476112,M,180,13,107.618664,"Minahassa Peninsula, Sulawesi",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176380,bmg2026nsai,2026-07-14 20:34:15.492794+00:00,-2.743634,129.173599,3.256532,M,18,14,108.371223,"Seram, Indonesia",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176381,bmg2026nsba,2026-07-14 20:56:11.729362+00:00,1.759947,122.211578,4.238763,M,10,17,212.534500,"Minahassa Peninsula, Sulawesi",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176382,bmg2026nseu,2026-07-14 22:50:13.246583+00:00,-20.824007,-178.249603,7.334316,Mw,254,1,360.000000,Fiji Islands Region,...,0.999411,0.000589,270.176592,89.834714,172.557351,0.198184,82.557382,0.166691,360.0,0.082207
176383,bmg2026nsha,2026-07-14 23:58:03.041589+00:00,-2.614751,139.089417,4.662608,M,13,17,105.460907,Near North Coast of West Papua,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### 2. names ---> names is going to take a list of names that we can provide to our column names

#### ----> names = ['Name','Age']

#### we can change the names

In [14]:
pd.read_csv('Titanic-Dataset.csv',names = ['P_ID','Survived','P_Class','P_Name','Gender','Age','Sibling or Spouse','Parch','Ticket_ID','Fare','Cabin','Starting Journey'])

,P_ID,Survived,P_Class,P_Name,Gender,Age,Sibling or Spouse,Parch,Ticket_ID,Fare,Cabin,Starting Journey
0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.25,NaN,S
2,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
3,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.925,NaN,S
4,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1,C123,S
...,...,...,...,...,...,...,...,...,...,...,...,...
887,887,0,2,"Montvila, Rev. Juozas",male,27,0,0,211536,13,NaN,S
888,888,1,1,"Graham, Miss. Margaret Edith",female,19,0,0,112053,30,B42,S
889,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
890,890,1,1,"Behr, Mr. Karl Howell",male,26,0,0,111369,30,C148,C
891,891,0,3,"Dooley, Mr. Patrick",male,32,0,0,370376,7.75,NaN,Q

### 3. header --- > header paramter makes sure that any of the row name will be shown as the column name only based on indexing of

In [3]:
pd.read_csv('Titanic-Dataset.csv',header = 1)

,1,0,3,"Braund, Mr. Owen Harris",male,22,1.1,0.1,A/5 21171,7.25,Unnamed: 10,S
0,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
1,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
3,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
4,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
885,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
886,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
887,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
888,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
889,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### 4. any column as the index 
#### index_col ---> keep one of the our column as the index ?

In [5]:
pd.read_csv('Titanic-Dataset.csv',index_col='PassengerId')

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [6]:
pd.read_csv('Titanic-Dataset.csv')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### 5. usecols ---> parameters

In [7]:
pd.read_csv('Titanic-Dataset.csv',usecols=['PassengerId','Survived','Name'])

     PassengerId  Survived                                               Name
0              1         0                            Braund, Mr. Owen Harris
1              2         1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2              3         1                             Heikkinen, Miss. Laina
3              4         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4              5         0                           Allen, Mr. William Henry
..           ...       ...                                                ...
886          887         0                              Montvila, Rev. Juozas
887          888         1                       Graham, Miss. Margaret Edith
888          889         0           Johnston, Miss. Catherine Helen "Carrie"
889          890         1                              Behr, Mr. Karl Howell
890          891         0                                Dooley, Mr. Patrick

[891 rows x 3 columns]

### 6. squeeze ----> dataframe ---> series ----> squeeze ----> True ---> Combination of usecols and squeeze

represent the dataframe into series

In [3]:
pd.read_csv('Titanic-Dataset.csv',usecols=['Survived']).squeeze()

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [5]:
pd.read_csv('Titanic-Dataset.csv')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### 7. nrows ---> It is going to help us with afixed number of rows out of the complete data ---> 100 only 100 rows out of all rows are shown

In [6]:
pd.read_csv('Titanic-Dataset.csv',nrows=100)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,0,3,"Shorney, Mr. Charles Joseph",male,NaN,0,0,374910,8.0500,NaN,S
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
97,98,1,1,"Greenfield, Mr. William Bertram",male,23.0,0,1,PC 17759,63.3583,D10 D12,C
98,99,1,2,"Doling, Mrs. John T (Ada Julia Bone)",female,34.0,0,1,231919,23.0000,NaN,S
99,100,0,2,"Kantor, Mr. Sinai",male,34.0,1,0,244367,26.0000,NaN,S

### We will face some encoding issues ----> utf-8 format
### We have to manually kee the encoding to utf-8 ---> to read the content from the dataset

### 8. encoding --- > It makes sure that the data we are reading is in utf-8 format ---- > encoding='latin-1'

In [7]:
pd.read_csv('Titanic-Dataset.csv',encoding='latin-1')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### 9. error_bad_lines ---> 
### in a dataset some rows will have 8 values and while others have 9 values so now those 8 values are removed to maintain the equal rows

In [ ]:
pd.read_csv('Titanic-Dataset.csv',error_bad_lines=False)

TypeError: read_csv() got an unexpected keyword argument 'error_bad_lines'. Did you mean 'on_bad_lines'?

### here it will be error because all rows are of equal

### 10. dtype ---> parameters ---> It can assign initally only with a specific datatypes to a column

###  syntax ---> dtypes(['col_1':int,'col_2':float])

In [15]:
pd.read_csv('Titanic-Dataset.csv',dtype={'Parch':float})

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0.0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0.0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0.0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0.0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0.0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0.0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0.0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2.0,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0.0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0.0,370376,7.7500,NaN,Q

### 11. parse_dates=['']

### to convert any columns into the date format

In [18]:
tsv

,eventID,datetime,latitude,longitude,magnitude,mag_type,depth,phasecount,azimuth_gap,location,...,doubleCouple,clvd,strikeNP1,dipNP1,rakeNP1,strikeNP2,dipNP2,rakeNP2,azgapFM,misfit
0,bmg2008vkye,2008-11-01 00:31:25.143741+00:00,-0.604440,98.895531,2.989742,MLv,20,6,146.707380,"Southern Sumatra, Indonesia",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,bmg2008vkzn,2008-11-01 01:13:15.738091+00:00,-3.386660,148.874180,5.208121,mb,51,38,190.275630,Bismarck Sea,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,bmg2008vlag,2008-11-01 01:34:29.660856+00:00,-6.611860,129.387220,5.507549,mb,30,62,45.467640,Banda Sea,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,bmg2008vlaj,2008-11-01 01:38:14.802129+00:00,-3.650586,127.990680,3.539674,MLv,5,4,331.974040,"Seram, Indonesia",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,bmg2008vlbt,2008-11-01 02:20:05.909515+00:00,-4.198925,128.097000,2.424314,MLv,5,5,326.379930,Banda Sea,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176379,bmg2026nsab,2026-07-14 20:26:41.769949+00:00,0.120709,122.167458,2.476112,M,180,13,107.618664,"Minahassa Peninsula, Sulawesi",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176380,bmg2026nsai,2026-07-14 20:34:15.492794+00:00,-2.743634,129.173599,3.256532,M,18,14,108.371223,"Seram, Indonesia",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176381,bmg2026nsba,2026-07-14 20:56:11.729362+00:00,1.759947,122.211578,4.238763,M,10,17,212.534500,"Minahassa Peninsula, Sulawesi",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176382,bmg2026nseu,2026-07-14 22:50:13.246583+00:00,-20.824007,-178.249603,7.334316,Mw,254,1,360.000000,Fiji Islands Region,...,0.999411,0.000589,270.176592,89.834714,172.557351,0.198184,82.557382,0.166691,360.0,0.082207
176383,bmg2026nsha,2026-07-14 23:58:03.041589+00:00,-2.614751,139.089417,4.662608,M,13,17,105.460907,Near North Coast of West Papua,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
tsv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 176384 entries, 0 to 176383
Data columns (total 37 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   eventID            176384 non-null  object
 1   datetime           176384 non-null  object
 2   latitude           176384 non-null  float64
 3   longitude          176384 non-null  float64
 4   magnitude          174979 non-null  float64
 5   mag_type           174979 non-null  object
 6   depth              176384 non-null  int64
 7   phasecount         176384 non-null  int64
 8   azimuth_gap        176380 non-null  float64
 9   location           176356 non-null  object
 10  agency             172448 non-null  object
 11  datetimeFM         8023 non-null    object
 12  latFM              8023 non-null    float64
 13  lonFM              8023 non-null    float64
 14  magFM              6618 non-null    float64
 15  magTypeFM          6618 non-null    object
 16  depthFM            8023 non-null    float64
 17  phasecountFM       8023 non-null    float64
 18  AzGapFM            7845 non-null    float64
 19  scalarMoment       7845 non-null    float64
 20  Mrr                7845 non-null    float64
 21  Mtt                7845 non-null    float64
 22  Mpp                7845 non-null    float64
 23  Mrt                7845 non-null    float64
 24  Mrp                7845 non-null    float64
 25  Mtp                7845 non-null    float64
 26  varianceReduction  7834 non-null    float64
 27  doubleCouple       7845 non-null    float64
 28  clvd               7845 non-null    float64
 29  strikeNP1          8023 non-null    float64
 30  dipNP1             8023 non-null    float64
 31  rakeNP1            8023 non-null    float64
 32  strikeNP2          8023 non-null    float64
 33  dipNP2             8023 non-null    float64
 34  rakeNP2            8023 non-null    float64
 35  azgapFM            7845 non-null    float64
 36  misfit             7834 non-null    float64
dtypes: float64(28), int64(2), object(7)
memory usage: 49.8+ MB

### here the datatime datatype should be of datetime format right

In [21]:
tsv = pd.read_csv('katalog_gempa_v2.tsv',sep='\t',parse_dates =['datetime'])

C:\Users\ASUS\AppData\Local\Temp\ipykernel_1188\2383391351.py:1: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  tsv = pd.read_csv('katalog_gempa_v2.tsv',sep='\t',parse_dates =['datetime'])

In [22]:
tsv

,eventID,datetime,latitude,longitude,magnitude,mag_type,depth,phasecount,azimuth_gap,location,...,doubleCouple,clvd,strikeNP1,dipNP1,rakeNP1,strikeNP2,dipNP2,rakeNP2,azgapFM,misfit
0,bmg2008vkye,2008-11-01 00:31:25.143741+00:00,-0.604440,98.895531,2.989742,MLv,20,6,146.707380,"Southern Sumatra, Indonesia",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,bmg2008vkzn,2008-11-01 01:13:15.738091+00:00,-3.386660,148.874180,5.208121,mb,51,38,190.275630,Bismarck Sea,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,bmg2008vlag,2008-11-01 01:34:29.660856+00:00,-6.611860,129.387220,5.507549,mb,30,62,45.467640,Banda Sea,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,bmg2008vlaj,2008-11-01 01:38:14.802129+00:00,-3.650586,127.990680,3.539674,MLv,5,4,331.974040,"Seram, Indonesia",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,bmg2008vlbt,2008-11-01 02:20:05.909515+00:00,-4.198925,128.097000,2.424314,MLv,5,5,326.379930,Banda Sea,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176379,bmg2026nsab,2026-07-14 20:26:41.769949+00:00,0.120709,122.167458,2.476112,M,180,13,107.618664,"Minahassa Peninsula, Sulawesi",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176380,bmg2026nsai,2026-07-14 20:34:15.492794+00:00,-2.743634,129.173599,3.256532,M,18,14,108.371223,"Seram, Indonesia",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176381,bmg2026nsba,2026-07-14 20:56:11.729362+00:00,1.759947,122.211578,4.238763,M,10,17,212.534500,"Minahassa Peninsula, Sulawesi",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176382,bmg2026nseu,2026-07-14 22:50:13.246583+00:00,-20.824007,-178.249603,7.334316,Mw,254,1,360.000000,Fiji Islands Region,...,0.999411,0.000589,270.176592,89.834714,172.557351,0.198184,82.557382,0.166691,360.0,0.082207
176383,bmg2026nsha,2026-07-14 23:58:03.041589+00:00,-2.614751,139.089417,4.662608,M,13,17,105.460907,Near North Coast of West Papua,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
tsv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 176384 entries, 0 to 176383
Data columns (total 37 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   eventID            176384 non-null  object
 1   datetime           176384 non-null  object
 2   latitude           176384 non-null  float64
 3   longitude          176384 non-null  float64
 4   magnitude          174979 non-null  float64
 5   mag_type           174979 non-null  object
 6   depth              176384 non-null  int64
 7   phasecount         176384 non-null  int64
 8   azimuth_gap        176380 non-null  float64
 9   location           176356 non-null  object
 10  agency             172448 non-null  object
 11  datetimeFM         8023 non-null    object
 12  latFM              8023 non-null    float64
 13  lonFM              8023 non-null    float64
 14  magFM              6618 non-null    float64
 15  magTypeFM          6618 non-null    object
 16  depthFM            8023 non-null    float64
 17  phasecountFM       8023 non-null    float64
 18  AzGapFM            7845 non-null    float64
 19  scalarMoment       7845 non-null    float64
 20  Mrr                7845 non-null    float64
 21  Mtt                7845 non-null    float64
 22  Mpp                7845 non-null    float64
 23  Mrt                7845 non-null    float64
 24  Mrp                7845 non-null    float64
 25  Mtp                7845 non-null    float64
 26  varianceReduction  7834 non-null    float64
 27  doubleCouple       7845 non-null    float64
 28  clvd               7845 non-null    float64
 29  strikeNP1          8023 non-null    float64
 30  dipNP1             8023 non-null    float64
 31  rakeNP1            8023 non-null    float64
 32  strikeNP2          8023 non-null    float64
 33  dipNP2             8023 non-null    float64
 34  rakeNP2            8023 non-null    float64
 35  azgapFM            7845 non-null    float64
 36  misfit             7834 non-null    float64
dtypes: float64(28), int64(2), object(7)
memory usage: 49.8+ MB

In [31]:
pd.read_csv('Chocolate Sales.csv',parse_dates=['Date']).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1094 entries, 0 to 1093
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sales Person   1094 non-null   object
 1   Country        1094 non-null   object
 2   Product        1094 non-null   object
 3   Date           1094 non-null   datetime64[ns]
 4   Amount         1094 non-null   object
 5   Boxes Shipped  1094 non-null   int64
dtypes: datetime64[ns](1), int64(1), object(4)
memory usage: 51.4+ KB

C:\Users\ASUS\AppData\Local\Temp\ipykernel_1188\4077701588.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.read_csv('Chocolate Sales.csv',parse_dates=['Date']).info()

### 12. Convertor
### it is acheived by the functions
### to change the value in specific row and column

In [33]:
pd.read_csv('Titanic-Dataset.csv')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [34]:
def station(value):
    if value == 'Q':
        return 'Queenstown'
    else:
        return value

In [42]:
pd.read_csv('Titanic-Dataset.csv',converters = {'Embarked':station})

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Queenstown

### 13. na_values
### Handling with misssing values like NaN values
### Considering all missing vaalues not only NaN values
### na_values helps us out with mentioning what values to be considered as a missing value
### syntax = na_values['\',':','No',NaN]

In [45]:
pd.read_csv('Titanic-Dataset.csv',na_values = ['NaN','No'])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### Loading a Huge Dataset in Chunks ---> chunksize_value ----> 20000----> 5000 in every dataframe ---> chunksize = 5000

In [46]:
dfs = pd.read_csv('Student Depression Dataset.csv',chunksize=5000)

In [47]:
for chunks in dfs:
    print(chunks.shape)

(5000, 18)
(5000, 18)
(5000, 18)
(5000, 18)
(5000, 18)
(2901, 18)