# DataFrames

### Dataframes can be created in 3 ways

### 1. lists ---> we can create dataframes
### 2. dictionary ---> we can create dataframes
### 3. read_csv() ---> creating an dataframe

## ---> dataframe is a combination of rows and columns --> 2d data structure

### 1. through lists

In [1]:
rows = [[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]]

# 1,2,3
# 4,5,6
# 7,8,9

In [2]:
import pandas as pd

In [3]:
list_data = pd.DataFrame(rows , columns=['a','b','c'])
list_data

    a   b   c
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12
4  13  14  15

In [4]:
list_data.shape # 5 rows and 3 columns

(5, 3)

### 2. through dictionary

In [5]:
## in case of dict both rows and columns should be mentioned

In [6]:
dict_data = {'Name':['Sailesh','Vivek','Gukesh'],'Money' : [1,5,7], 'Financial_Stress' : [1,1,0]}

In [7]:
dict_dataframe = pd.DataFrame(dict_data)

In [8]:
dict_dataframe

      Name  Money  Financial_Stress
0  Sailesh      1                 1
1    Vivek      5                 1
2   Gukesh      7                 0

### 3. through read_csv()

In [9]:
df = pd.read_csv('Student Depression Dataset.csv')

In [10]:
df

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

## Data Exploration ----> Attributes & Functions for the dataframe

## Attributes

### 1. .shape ---> it provide (rows,columns)

In [11]:
df.shape

(27901, 18)

### 2. .dtype ---> type of data in all columns

In [12]:
df.dtypes

id                                         int64
Gender                                       str
Age                                      float64
City                                         str
Profession                                   str
Academic Pressure                        float64
Work Pressure                            float64
CGPA                                     float64
Study Satisfaction                       float64
Job Satisfaction                         float64
Sleep Duration                               str
Dietary Habits                               str
Degree                                       str
Have you ever had suicidal thoughts ?        str
Work/Study Hours                         float64
Financial Stress                         float64
Family History of Mental Illness             str
Depression                                 int64
dtype: object

### 3. .index ---> for a dataframe with labelled index we can get the idea about the label just by using index attribute

In [13]:
df.index

RangeIndex(start=0, stop=27901, step=1)

### 4. .columns ---> it provides the idea about the all of the column names of the given dataframe

In [14]:
df.columns ## gives names of all the columns

Index(['id', 'Gender', 'Age', 'City', 'Profession', 'Academic Pressure',
       'Work Pressure', 'CGPA', 'Study Satisfaction', 'Job Satisfaction',
       'Sleep Duration', 'Dietary Habits', 'Degree',
       'Have you ever had suicidal thoughts ?', 'Work/Study Hours',
       'Financial Stress', 'Family History of Mental Illness', 'Depression'],
      dtype='str')

### 5. .values ---> it provides the idea about the values present row by row inside the dataframe

### ---. it allways returns a numpy array representing of the values of column row by row

In [15]:
df.values

array([[2, 'Male', 33.0, ..., 1.0, 'No', 1],
       [8, 'Female', 24.0, ..., 2.0, 'Yes', 0],
       [26, 'Male', 31.0, ..., 1.0, 'Yes', 0],
       ...,
       [140689, 'Male', 31.0, ..., 2.0, 'No', 0],
       [140690, 'Female', 18.0, ..., 5.0, 'No', 1],
       [140699, 'Male', 27.0, ..., 3.0, 'Yes', 1]],
      shape=(27901, 18), dtype=object)

In [16]:
df.values[0]

array([2, 'Male', 33.0, 'Visakhapatnam', 'Student', 5.0, 0.0, 8.97, 2.0,
       0.0, '5-6 hours', 'Healthy', 'B.Pharm', 'Yes', 3.0, 1.0, 'No', 1],
      dtype=object)

In [17]:
df.values[17]

array([132, 'Female', 20.0, 'Ahmedabad', 'Student', 5.0, 0.0, 7.25, 3.0,
       0.0, '5-6 hours', 'Healthy', 'Class 12', 'Yes', 10.0, 3.0, 'No', 1],
      dtype=object)

### 6. .ndim ---> it provides the idea about the dimension of the dataframe

In [18]:
df.ndim

2

### 7. .size ---> provides the idea about the total no:of elements present inside the dataframe

In [19]:
df.shape

(27901, 18)

In [20]:
a = 27901 * 18
print(a)

502218

In [21]:
df.size

502218

## Functions

### 1. head() --- > to get to have the idea about the data that your dataset is storing as thetop 5 rows , that means that starting from the top we can get the top 5 rows and along with thatif i want that instead of top 5 rows i want to see a fixed no . of rows from the rows , that number i can pass inside the head() as a parameter

In [22]:
df

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

In [23]:
df.head()

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0

In [24]:
df.head(10)

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
5,33,Male,29.0,Pune,Student,2.0,0.0,5.70,3.0,0.0,Less than 5 hours,Healthy,PhD,No,4.0,1.0,No,0
6,52,Male,30.0,Thane,Student,3.0,0.0,9.54,4.0,0.0,7-8 hours,Healthy,BSc,No,1.0,2.0,No,0
7,56,Female,30.0,Chennai,Student,2.0,0.0,8.04,4.0,0.0,Less than 5 hours,Unhealthy,Class 12,No,0.0,1.0,Yes,0
8,59,Male,28.0,Nagpur,Student,3.0,0.0,9.79,1.0,0.0,7-8 hours,Moderate,B.Ed,Yes,12.0,3.0,No,1
9,62,Male,31.0,Nashik,Student,2.0,0.0,8.38,3.0,0.0,Less than 5 hours,Moderate,LLB,Yes,2.0,5.0,No,1

### 2. tail()

In [25]:
df.tail()

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

### 3. sample()

In [26]:
df.sample()

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
23637,119081,Male,32.0,Chennai,Student,1.0,0.0,5.27,3.0,0.0,5-6 hours,Healthy,MBBS,No,11.0,4.0,Yes,0

In [27]:
df.sample(5)

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
14952,75402,Female,28.0,Varanasi,Student,1.0,0.0,7.32,1.0,0.0,5-6 hours,Healthy,LLM,Yes,7.0,2.0,No,1
14023,70998,Male,32.0,Kalyan,Student,1.0,0.0,9.74,1.0,0.0,5-6 hours,Healthy,BHM,No,9.0,4.0,No,0
23513,118468,Male,18.0,Thane,Student,5.0,0.0,6.47,2.0,0.0,7-8 hours,Unhealthy,Class 12,No,5.0,5.0,Yes,1
10506,53232,Female,30.0,Kalyan,Student,3.0,0.0,7.82,1.0,0.0,5-6 hours,Healthy,M.Ed,Yes,4.0,3.0,No,1
6541,32810,Female,19.0,Hyderabad,Student,2.0,0.0,5.56,3.0,0.0,More than 8 hours,Healthy,Class 12,No,10.0,4.0,Yes,1

### 4. info() ---> this function provides the idea about the data type of all columns & also about the no:of missing values of all columns & also about the memory storage of the

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 27901 entries, 0 to 27900
Data columns (total 18 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   id                                     27901 non-null  int64
 1   Gender                                 27901 non-null  str
 2   Age                                    27901 non-null  float64
 3   City                                   27901 non-null  str
 4   Profession                             27901 non-null  str
 5   Academic Pressure                      27901 non-null  float64
 6   Work Pressure                          27901 non-null  float64
 7   CGPA                                   27901 non-null  float64
 8   Study Satisfaction                     27901 non-null  float64
 9   Job Satisfaction                       27901 non-null  float64
 10  Sleep Duration                         27901 non-null  str
 11  Dietary Habits                         27901 non-null  str
 12  Degree                                 27901 non-null  str
 13  Have you ever had suicidal thoughts ?  27901 non-null  str
 14  Work/Study Hours                       27901 non-null  float64
 15  Financial Stress                       27898 non-null  float64
 16  Family History of Mental Illness       27901 non-null  str
 17  Depression                             27901 non-null  int64
dtypes: float64(8), int64(2), str(8)
memory usage: 5.2 MB

### 5. describe()

In [29]:
df.describe()

,id,Age,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Work/Study Hours,Financial Stress,Depression
count,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27901.000000,27898.000000,27901.000000
mean,70442.149421,25.822300,3.141214,0.000430,7.656104,2.943837,0.000681,7.156984,3.139867,0.585499
std,40641.175216,4.905687,1.381465,0.043992,1.470707,1.361148,0.044394,3.707642,1.437347,0.492645
min,2.000000,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
25%,35039.000000,21.000000,2.000000,0.000000,6.290000,2.000000,0.000000,4.000000,2.000000,0.000000
50%,70684.000000,25.000000,3.000000,0.000000,7.770000,3.000000,0.000000,8.000000,3.000000,1.000000
75%,105818.000000,30.000000,4.000000,0.000000,8.920000,4.000000,0.000000,10.000000,4.000000,1.000000
max,140699.000000,59.000000,5.000000,5.000000,10.000000,5.000000,4.000000,12.000000,5.000000,1.000000

### Before data cleaning, we must have the idea about whether if data having any missing value or not

## Data cleaning
## 1. Missing Values
## 2. Duplicate
## 3. Renaming the column as well

### 1. Missing value or not checking ---> isnull()

In [30]:
df.isnull()

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
27897,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
27898,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
27899,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
27900,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [31]:
df.isnull().count()

id                                       27901
Gender                                   27901
Age                                      27901
City                                     27901
Profession                               27901
Academic Pressure                        27901
Work Pressure                            27901
CGPA                                     27901
Study Satisfaction                       27901
Job Satisfaction                         27901
Sleep Duration                           27901
Dietary Habits                           27901
Degree                                   27901
Have you ever had suicidal thoughts ?    27901
Work/Study Hours                         27901
Financial Stress                         27901
Family History of Mental Illness         27901
Depression                               27901
dtype: int64

In [32]:
data = {'name':['Sailesh','Amit'],'package': [8,9],'degree' : ['Btech',None]}

In [33]:
data_df = pd.DataFrame(data)
data_df

      name  package degree
0  Sailesh        8  Btech
1     Amit        9    NaN

In [34]:
data_df.isnull()

    name  package  degree
0  False    False   False
1  False    False    True

In [35]:
data_df.isnull().sum()

name       0
package    0
degree     1
dtype: int64

##### ---> missing values are typically represented as nan values

### 2. duplicate values are present or not
### ---> duplicated()

In [36]:
data_df.duplicated()

0    False
1    False
dtype: bool

In [37]:
data_df.duplicated().sum()

np.int64(0)

In [38]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
27896    False
27897    False
27898    False
27899    False
27900    False
Length: 27901, dtype: bool

### 3. rename() ---> renaming the columns

In [39]:
df

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

In [40]:
df.rename(columns={'CGPA':'Cgpa'})

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,Cgpa,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

In [41]:
df

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

### inplace parameter

In [42]:
df.rename(columns = {'Age':'AGE'},inplace = True)

In [43]:
df

,id,Gender,AGE,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

## Mathematical Functions in data frames

## Mathematical Functions in DataFrame

#### 1. sum() ---- > it calculates the sum of all values present in a column or in muliple columns

#### 2. mean() --- > it calculates the average of all values or mean of all values in a column

#### 3. min() ---- > it calculates the minimum values of a column

#### 4. max() --- > it calculates the maximum value of a column

#### 5. median() --- > it calculates the median value of a column

#### 6. var() ---- > it calculates the variance of all values of a column

#### axis parameter ----> helps us calculate the mathematical calculation row wise or column wise

#### mathematical operation ---> row wise ---> axis=1
#### mathematical operation ---> column wise ---> axis=0

In [44]:
df.sum()

id                                                                              1965406411
Gender                                   MaleFemaleMaleFemaleFemaleMaleMaleFemaleMaleMa...
AGE                                                                               720468.0
City                                     VisakhapatnamBangaloreSrinagarVaranasiJaipurPu...
Profession                               StudentStudentStudentStudentStudentStudentStud...
Academic Pressure                                                                  87643.0
Work Pressure                                                                         12.0
CGPA                                                                           213612.9625
Study Satisfaction                                                                 82136.0
Job Satisfaction                                                                      19.0
Sleep Duration                           5-6 hours5-6 hoursLess than 5 hours7-8 hours5-...
Dietary Habits                           HealthyModerateHealthyModerateModerateHealthyH...
Degree                                   B.PharmBScBABCAM.TechPhDBScClass 12B.EdLLBClas...
Have you ever had suicidal thoughts ?    YesNoNoYesYesNoNoNoYesYesYesYesNoNoYesYesYesYe...
Work/Study Hours                                                                  199687.0
Financial Stress                                                                   87596.0
Family History of Mental Illness         NoYesYesYesNoNoNoYesNoNoYesYesYesYesYesYesYesN...
Depression                                                                           16336
dtype: object

In [45]:
df.values[0]

array([2, 'Male', 33.0, 'Visakhapatnam', 'Student', 5.0, 0.0, 8.97, 2.0,
       0.0, '5-6 hours', 'Healthy', 'B.Pharm', 'Yes', 3.0, 1.0, 'No', 1],
      dtype=object)

In [46]:
df.sum(axis=0) ## column wise

id                                                                              1965406411
Gender                                   MaleFemaleMaleFemaleFemaleMaleMaleFemaleMaleMa...
AGE                                                                               720468.0
City                                     VisakhapatnamBangaloreSrinagarVaranasiJaipurPu...
Profession                               StudentStudentStudentStudentStudentStudentStud...
Academic Pressure                                                                  87643.0
Work Pressure                                                                         12.0
CGPA                                                                           213612.9625
Study Satisfaction                                                                 82136.0
Job Satisfaction                                                                      19.0
Sleep Duration                           5-6 hours5-6 hoursLess than 5 hours7-8 hours5-...
Dietary Habits                           HealthyModerateHealthyModerateModerateHealthyH...
Degree                                   B.PharmBScBABCAM.TechPhDBScClass 12B.EdLLBClas...
Have you ever had suicidal thoughts ?    YesNoNoYesYesNoNoNoYesYesYesYesNoNoYesYesYesYe...
Work/Study Hours                                                                  199687.0
Financial Stress                                                                   87596.0
Family History of Mental Illness         NoYesYesYesNoNoNoYesNoNoYesYesYesYesYesYesYesN...
Depression                                                                           16336
dtype: object

In [47]:
df.sum(axis=1)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [ ]:
df.min()

id                                               2
Gender                                      Female
AGE                                           18.0
City                                           3.0
Profession                               Architect
Academic Pressure                              0.0
Work Pressure                                  0.0
CGPA                                           0.0
Study Satisfaction                             0.0
Job Satisfaction                               0.0
Sleep Duration                           5-6 hours
Dietary Habits                             Healthy
Degree                                      B.Arch
Have you ever had suicidal thoughts ?           No
Work/Study Hours                               0.0
Financial Stress                               1.0
Family History of Mental Illness                No
Depression                                       0
dtype: object

In [ ]:
df.max()

id                                               140699
Gender                                             Male
AGE                                                59.0
City                                      Visakhapatnam
Profession                               UX/UI Designer
Academic Pressure                                   5.0
Work Pressure                                       5.0
CGPA                                               10.0
Study Satisfaction                                  5.0
Job Satisfaction                                    4.0
Sleep Duration                                   Others
Dietary Habits                                Unhealthy
Degree                                              PhD
Have you ever had suicidal thoughts ?               Yes
Work/Study Hours                                   12.0
Financial Stress                                    5.0
Family History of Mental Illness                    Yes
Depression                                            1
dtype: object

In [ ]:
df.median()

TypeError: Cannot perform reduction 'median' with string dtype

In [ ]:
df.var()

TypeError: Cannot perform reduction 'var' with string dtype

In [ ]:
df

,id,Gender,AGE,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

#### selecting a column from the dataframe

In [ ]:
df['Academic Pressure']

0        5.0
1        2.0
2        3.0
3        3.0
4        4.0
        ...
27896    5.0
27897    2.0
27898    3.0
27899    5.0
27900    4.0
Name: Academic Pressure, Length: 27901, dtype: float64

In [ ]:
type(df['Academic Pressure'])

pandas.Series

#### selecting multiple columns from the dataset

In [ ]:
df[['id','AGE','Gender']]

           id   AGE  Gender
0           2  33.0    Male
1           8  24.0  Female
2          26  31.0    Male
3          30  28.0  Female
4          32  25.0  Female
...       ...   ...     ...
27896  140685  27.0  Female
27897  140686  27.0    Male
27898  140689  31.0    Male
27899  140690  18.0  Female
27900  140699  27.0    Male

[27901 rows x 3 columns]

## Select the specific rows of our Dataframe ----> loc[] and iloc[]

#### loc[] --- > location --- > it fetches the record as per the labelled index location of the value
#### iloc[] --- > integer location ---- > it fetches the record as per the integer index location of the value

In [50]:
df.iloc[200]

id                                                     965
Gender                                              Female
AGE                                                   30.0
City                                               Kolkata
Profession                                         Student
Academic Pressure                                      1.0
Work Pressure                                          0.0
CGPA                                                  8.54
Study Satisfaction                                     3.0
Job Satisfaction                                       0.0
Sleep Duration                           Less than 5 hours
Dietary Habits                                    Moderate
Degree                                                M.Ed
Have you ever had suicidal thoughts ?                   No
Work/Study Hours                                      12.0
Financial Stress                                       1.0
Family History of Mental Illness                       Yes
Depression                                               0
Name: 200, dtype: object

In [51]:
df.iloc[5000]

id                                           25074
Gender                                        Male
AGE                                           18.0
City                                       Chennai
Profession                                 Student
Academic Pressure                              5.0
Work Pressure                                  0.0
CGPA                                          5.86
Study Satisfaction                             1.0
Job Satisfaction                               0.0
Sleep Duration                           7-8 hours
Dietary Habits                           Unhealthy
Degree                                    Class 12
Have you ever had suicidal thoughts ?           No
Work/Study Hours                              11.0
Financial Stress                               4.0
Family History of Mental Illness                No
Depression                                       1
Name: 5000, dtype: object

## We can Fetch the records by slicing concept in iloc[]

In [53]:
df.iloc[0:11]

,id,Gender,AGE,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
5,33,Male,29.0,Pune,Student,2.0,0.0,5.70,3.0,0.0,Less than 5 hours,Healthy,PhD,No,4.0,1.0,No,0
6,52,Male,30.0,Thane,Student,3.0,0.0,9.54,4.0,0.0,7-8 hours,Healthy,BSc,No,1.0,2.0,No,0
7,56,Female,30.0,Chennai,Student,2.0,0.0,8.04,4.0,0.0,Less than 5 hours,Unhealthy,Class 12,No,0.0,1.0,Yes,0
8,59,Male,28.0,Nagpur,Student,3.0,0.0,9.79,1.0,0.0,7-8 hours,Moderate,B.Ed,Yes,12.0,3.0,No,1
9,62,Male,31.0,Nashik,Student,2.0,0.0,8.38,3.0,0.0,Less than 5 hours,Moderate,LLB,Yes,2.0,5.0,No,1
10,83,Male,24.0,Nagpur,Student,3.0,0.0,6.10,3.0,0.0,5-6 hours,Moderate,Class 12,Yes,11.0,1.0,Yes,1

In [54]:
df.iloc[8:]

,id,Gender,AGE,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
8,59,Male,28.0,Nagpur,Student,3.0,0.0,9.79,1.0,0.0,7-8 hours,Moderate,B.Ed,Yes,12.0,3.0,No,1
9,62,Male,31.0,Nashik,Student,2.0,0.0,8.38,3.0,0.0,Less than 5 hours,Moderate,LLB,Yes,2.0,5.0,No,1
10,83,Male,24.0,Nagpur,Student,3.0,0.0,6.10,3.0,0.0,5-6 hours,Moderate,Class 12,Yes,11.0,1.0,Yes,1
11,91,Male,33.0,Vadodara,Student,3.0,0.0,7.03,4.0,0.0,Less than 5 hours,Healthy,BE,Yes,10.0,2.0,Yes,0
12,94,Male,27.0,Kalyan,Student,5.0,0.0,7.04,1.0,0.0,Less than 5 hours,Moderate,M.Tech,No,10.0,1.0,Yes,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

## slicing with skipping values

In [56]:
df.iloc[::2]

,id,Gender,AGE,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
6,52,Male,30.0,Thane,Student,3.0,0.0,9.54,4.0,0.0,7-8 hours,Healthy,BSc,No,1.0,2.0,No,0
8,59,Male,28.0,Nagpur,Student,3.0,0.0,9.79,1.0,0.0,7-8 hours,Moderate,B.Ed,Yes,12.0,3.0,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27892,140669,Female,20.0,Indore,Student,3.0,0.0,7.72,5.0,0.0,Less than 5 hours,Moderate,Class 12,Yes,8.0,1.0,No,0
27894,140681,Male,23.0,Srinagar,Student,3.0,0.0,6.00,2.0,0.0,More than 8 hours,Healthy,MBBS,Yes,12.0,4.0,No,0
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

### loc[] --> passing on the location of given index

In [57]:
data

{'name': ['Sailesh', 'Amit'], 'package': [8, 9], 'degree': ['Btech', None]}

### set_index() ---> itcan help you out with setting a specific column as the index of dataframe

In [58]:
df.head(5)

,id,Gender,AGE,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0

In [60]:
data = pd.DataFrame(data)
data

      name  package degree
0  Sailesh        8  Btech
1     Amit        9    NaN

In [64]:
data = data.set_index('name')

In [65]:
data.loc['Sailesh']

package        8
degree     Btech
Name: Sailesh, dtype: object

### fancy indexing

In [66]:
## fancy indexing is possible in fetching records

In [69]:
df.iloc[[1,4,5,6]]

,id,Gender,AGE,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
5,33,Male,29.0,Pune,Student,2.0,0.0,5.70,3.0,0.0,Less than 5 hours,Healthy,PhD,No,4.0,1.0,No,0
6,52,Male,30.0,Thane,Student,3.0,0.0,9.54,4.0,0.0,7-8 hours,Healthy,BSc,No,1.0,2.0,No,0

In [70]:
data

         package degree
name
Sailesh        8  Btech
Amit           9    NaN

In [74]:
data.loc['Sailesh']

package        8
degree     Btech
Name: Sailesh, dtype: object

In [75]:
data.loc['Sailesh' : ]

         package degree
name
Sailesh        8  Btech
Amit           9    NaN

#### even if we are having the laballed index in the backend the labelled index is also having the integer indexing at the backend

str ----> indirectly refers to the int

In [77]:
data.loc[0] ## at backend 'Sailesh' ---> 0

KeyError: 0

In [78]:
df

,id,Gender,AGE,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,Female,27.0,Surat,Student,5.0,0.0,5.75,5.0,0.0,5-6 hours,Unhealthy,Class 12,Yes,7.0,1.0,Yes,0
27897,140686,Male,27.0,Ludhiana,Student,2.0,0.0,9.40,3.0,0.0,Less than 5 hours,Healthy,MSc,No,0.0,3.0,Yes,0
27898,140689,Male,31.0,Faridabad,Student,3.0,0.0,6.61,4.0,0.0,5-6 hours,Unhealthy,MD,No,12.0,2.0,No,0
27899,140690,Female,18.0,Ludhiana,Student,5.0,0.0,6.88,2.0,0.0,Less than 5 hours,Healthy,Class 12,Yes,10.0,5.0,No,1
27900,140699,Male,27.0,Patna,Student,4.0,0.0,9.24,1.0,0.0,Less than 5 hours,Healthy,BCA,Yes,2.0,3.0,Yes,1

### if we want specific row and specific column

In [80]:
df.columns

Index(['id', 'Gender', 'AGE', 'City', 'Profession', 'Academic Pressure',
       'Work Pressure', 'CGPA', 'Study Satisfaction', 'Job Satisfaction',
       'Sleep Duration', 'Dietary Habits', 'Degree',
       'Have you ever had suicidal thoughts ?', 'Work/Study Hours',
       'Financial Stress', 'Family History of Mental Illness', 'Depression'],
      dtype='str')

In [79]:
## df[row1 : row2 , col1 : col2]
df.loc[1:5,'id':'Profession']

   id  Gender   AGE       City Profession
1   8  Female  24.0  Bangalore    Student
2  26    Male  31.0   Srinagar    Student
3  30  Female  28.0   Varanasi    Student
4  32  Female  25.0     Jaipur    Student
5  33    Male  29.0       Pune    Student

iloc[] ----> integer location

In [82]:
df.iloc[0:9,0:4]

   id  Gender   AGE           City
0   2    Male  33.0  Visakhapatnam
1   8  Female  24.0      Bangalore
2  26    Male  31.0       Srinagar
3  30  Female  28.0       Varanasi
4  32  Female  25.0         Jaipur
5  33    Male  29.0           Pune
6  52    Male  30.0          Thane
7  56  Female  30.0        Chennai
8  59    Male  28.0         Nagpur