In [2]:
pip install pandas

Requirement already satisfied: pandas in c:\users\asus\appdata\roaming\python\python312\site-packages (3.0.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\asus\appdata\roaming\python\python312\site-packages (from pandas) (2.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\asus\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\asus\appdata\roaming\python\python312\site-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in c:\users\asus\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import numpy as np
import pandas as pd

## Pandas Series

### Pandas Series is a column of data in a Table like in Excel or Google Sheets with labels called as indexes attached to each value .

### Data stored in Pandas series in labelled

In [4]:
pd.Series([40,50,60])

0    40
1    50
2    60
dtype: int64

#### Labelling

In [5]:
pd.Series([40,50,60],index = ['Bread','Milk','Buttter'])

Bread      40
Milk       50
Buttter    60
dtype: int64

#### naming

In [6]:
pd.Series([40,50,60],index = ['Bread','Milk','Buttter'], name = 'price of Grocessiries items')

Bread      40
Milk       50
Buttter    60
Name: price of Grocessiries items, dtype: int64

## Series is a 1D Array that can hold any type of the data like integers, float, strings (objects), boolean and mixed data types

#### Data type --- > Integers ----- > Data in a Series(Column) --- > Quantity of items in the Stock

#### Data type --- > Float ---- > Data in a Series(Column) --- > Price or Product Ratings

#### Data type --- > Strings --- > Column --- > Product Name

#### Data type --- > Boolean --- > Column --- > Is item in Stock ?

#### Data type --- > Dates/ Times --- > Column --- > Expiry Dates or Sale Dates

#### Mixed Types --- > Milk,40, True

## Creating a Series in Multiple Ways
1. List
2. Numpy Array
3. Dictionary
4. Custom Index
5. Scalar Value

### 1. List

In [7]:
country = ['India','china','USA','UK']

pd.Series(country)

0    India
1    china
2      USA
3       UK
dtype: str

In [8]:
runs_batsman = [100, 200, 300, 400]
pd.Series(runs_batsman)

0    100
1    200
2    300
3    400
dtype: int64

In [9]:
subject_names = ['Maths','Physics','Chemistry','Biology']
marks = [90, 80, 70, 60]
pd.Series(data = marks, index = subject_names, name = 'Marks of Students')

Maths        90
Physics      80
Chemistry    70
Biology      60
Name: Marks of Students, dtype: int64

### 2. Numpy

In [10]:
values = np.arange(10, 21)
pd.Series(values)

0     10
1     11
2     12
3     13
4     14
5     15
6     16
7     17
8     18
9     19
10    20
dtype: int64

### 3. Dictionary to series

### Dictionary is another data Structure that stores the data in a key value pair and just because it stroes the data in a key value pair so we don't have to explicitly mention the index

In [11]:
data_items = {'Maths': 90, 'Physics': 80, 'Chemistry': 70, 'Biology': 60}
pd.Series(data_items)

Maths        90
Physics      80
Chemistry    70
Biology      60
dtype: int64

### 4. Custom Index

In [12]:
values = [1,2,3,4,5]
pd.Series(data = values, index = ['a','b','c','d','e'])

a    1
b    2
c    3
d    4
e    5
dtype: int64

### 5. Scalar Value

In [13]:
## Scalar Values in Series
## same value is assigned to all the indexes in the series.

pd.Series(5, index = [0,1,2,3,4])

0    5
1    5
2    5
3    5
4    5
dtype: int64

## read_csv() ---> this function reads the content fromthe csv file in pandas so that we can perform the operations on the data or we can perform effective analysis

In [14]:
data1 = pd.read_csv('D:/GEN AI Dev/Machine Learning/DataSets/youtube_channel_info_v1.csv')
data1

,channel_name,channel_id,view_count,category,country,defaultLanguage,subscriber_count,created_date,description,custom_url,thumbnail,video_count
0,BLACKPINK,UCOmHUn--16B90oW2L6FRR3A,39962585446,"Music of Asia, Pop music, Music, Electronic music",KR,NaN,99000000,2016-06-29T03:15:23Z,BLACKPINK Official YouTube Channel 블랙핑크 공식 유튜브...,@blackpink,https://yt3.ggpht.com/U3VrCkKjzTpQ3VYv4SCPjNfD...,636
1,HYBE LABELS,UC3IZKseVpdzPSBaWxBxundA,41604896923,"Hip hop music, Pop music, Music, Music of Asia",KR,NaN,78700000,2008-06-04T08:23:22Z,Welcome to the official YouTube channel of HYB...,@hybelabels,https://yt3.ggpht.com/ytc/AIdro_l8g0yRFG8xoe_q...,2817
2,BILLIE EILISH,UCVNE660NcgYzi18LwwUZb7Q,14316364,NaN,NaN,NaN,82300,2019-01-18T05:14:32Z,NaN,@billieeilish8477,https://yt3.ggpht.com/ytc/AIdro_n3NfvUAVtcUJvW...,1
3,Shemaroo,UCF1JIbMUs6uqoZEY1Haw0GQ,27011004224,"Entertainment, Film",IN,NaN,60400000,2007-09-01T11:44:51Z,"Welcome to ShemarooEnt, one of the finest dest...",@shemaroo,https://yt3.ggpht.com/ytc/AIdro_mhdF4RNZM9OHP-...,13374
4,JuegaGerman,UCYiGq8XF7YQD00x7wAd62Zg,17573028501,"Role-playing video game, Action game, Video ga...",CL,NaN,54200000,2013-05-19T00:09:13Z,Lento pero seguro.,@juegagerman,https://yt3.ggpht.com/vOsrLzWD4z1dbr470nEXydi3...,2368
...,...,...,...,...,...,...,...,...,...,...,...,...
15825,Benchmark Entertainment,UCqsXkde84Zt4pp0NbYiWe_Q,79289853,"Hip hop music, Music, Music of Asia, Pop music...",IN,NaN,241000,2020-06-07T08:21:45.961094Z,"“Benchmark Entertainment, founded in the year ...",@benchmarkentertainment,https://yt3.ggpht.com/XGtEIDLXS8HO4wkrHZkLYtQ9...,43
15826,South China Morning Post,UC4SUWizzKc1tptprBkWjX2Q,4484864729,"Society, Politics",HK,NaN,4260000,2007-01-18T08:00:37Z,"Videos from Hong Kong, Greater China and beyon...",@southchinamorningpost,https://yt3.ggpht.com/4Q9yos_fKmzf0o36ETS4IZel...,19781
15827,reXpair,UCVNFzYxySA5UFvAi32vD0cg,2581715060,"Vehicle, Lifestyle (sociology)",US,NaN,2920000,2021-01-26T16:11:39.950855Z,reXpair brings evolution to tire repair. Easy ...,@rexpair,https://yt3.ggpht.com/ytc/AIdro_mo3h5ArO9cGpWH...,681
15828,Cher Lloyd,UC3hhq3Twc_jTYWzfL5BCa1A,1156418780,"Music, Pop music, Electronic music",GB,NaN,3250000,2010-12-03T11:19:40Z,GREEN LIGHT - Out Now 💚 Listen here: https://l...,@thecherlloydchannel,https://yt3.ggpht.com/8ULlM9qfcLPH3CQFyOJBK9J6...,82
15829,Paritosh Shorts,UCAt0ZufG7-TvfgbwkCbKd3Q,724470959,Entertainment,IN,NaN,2880000,2022-08-08T12:07:15.139731Z,"Hello Guys I’m Paritosh, दिल्ली Ka Content Cre...",@paritoshshorts,https://yt3.ggpht.com/BKye01LNtsTpU0zLrL-jRYKL...,639

In [15]:
data2 = pd.read_csv('youtube_channel_info_v2.csv')
data2

,channel_name,channel_id,view_count,category,country,defaultLanguage,subscriber_count,created_date,description,custom_url,thumbnail,video_count,videos_last_30_days,views_last_30_days,uploads_playlist_id,last_10_video_ids
0,BLACKPINK,UCOmHUn--16B90oW2L6FRR3A,39962585446,"Music of Asia, Pop music, Music, Electronic music",KR,NaN,99000000,2016-06-29T03:15:23Z,BLACKPINK Official YouTube Channel 블랙핑크 공식 유튜브...,@blackpink,https://yt3.ggpht.com/U3VrCkKjzTpQ3VYv4SCPjNfD...,636,1,3256869,UUOmHUn--16B90oW2L6FRR3A,"W-9-keHNwV8,pAeqY-TEZc0,WB_AOdAEuBM,zTnAvaoHR4..."
1,HYBE LABELS,UC3IZKseVpdzPSBaWxBxundA,41604896923,"Hip hop music, Pop music, Music, Music of Asia",KR,NaN,78700000,2008-06-04T08:23:22Z,Welcome to the official YouTube channel of HYB...,@hybelabels,https://yt3.ggpht.com/ytc/AIdro_l8g0yRFG8xoe_q...,2817,79,46074833,UU3IZKseVpdzPSBaWxBxundA,"NPqiynCpqgI,nbOuR-KYZy8,xf8N3JYEhV4,iIWKCYP2zY..."
2,BILLIE EILISH,UCVNE660NcgYzi18LwwUZb7Q,14316364,NaN,NaN,NaN,82300,2019-01-18T05:14:32Z,NaN,@billieeilish8477,https://yt3.ggpht.com/ytc/AIdro_n3NfvUAVtcUJvW...,1,0,0,UUVNE660NcgYzi18LwwUZb7Q,C9odQay_d6s
3,Shemaroo,UCF1JIbMUs6uqoZEY1Haw0GQ,27011004224,"Entertainment, Film",IN,NaN,60400000,2007-09-01T11:44:51Z,"Welcome to ShemarooEnt, one of the finest dest...",@shemaroo,https://yt3.ggpht.com/ytc/AIdro_mhdF4RNZM9OHP-...,13374,63,10560897,UUF1JIbMUs6uqoZEY1Haw0GQ,"KPYx-APpvo4,HscCQYIX4fg,TP64Sacd5Nw,G8a5vnD2A0..."
4,JuegaGerman,UCYiGq8XF7YQD00x7wAd62Zg,17573028501,"Role-playing video game, Action game, Video ga...",CL,NaN,54200000,2013-05-19T00:09:13Z,Lento pero seguro.,@juegagerman,https://yt3.ggpht.com/vOsrLzWD4z1dbr470nEXydi3...,2368,12,22980501,UUYiGq8XF7YQD00x7wAd62Zg,"JjWksJW1Z0M,_NhOyRPXA5s,EYXTxxjU0Ks,5eAyv6b84p..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15825,Benchmark Entertainment,UCqsXkde84Zt4pp0NbYiWe_Q,79289853,"Hip hop music, Music, Music of Asia, Pop music...",IN,NaN,241000,2020-06-07T08:21:45.961094Z,"“Benchmark Entertainment, founded in the year ...",@benchmarkentertainment,https://yt3.ggpht.com/XGtEIDLXS8HO4wkrHZkLYtQ9...,43,0,0,UUqsXkde84Zt4pp0NbYiWe_Q,"mjyaQOuqUGc,VTPA_AjHZMA,IfJL_u-gnio,5AJFf9eqJZ..."
15826,South China Morning Post,UC4SUWizzKc1tptprBkWjX2Q,4484864729,"Society, Politics",HK,NaN,4260000,2007-01-18T08:00:37Z,"Videos from Hong Kong, Greater China and beyon...",@southchinamorningpost,https://yt3.ggpht.com/4Q9yos_fKmzf0o36ETS4IZel...,19781,124,8120594,UU4SUWizzKc1tptprBkWjX2Q,"zSX826Tfkwo,fkKvagzbFRA,kHmmcpVPSUE,fFz5HWu0yh..."
15827,reXpair,UCVNFzYxySA5UFvAi32vD0cg,2581715060,"Vehicle, Lifestyle (sociology)",US,NaN,2920000,2021-01-26T16:11:39.950855Z,reXpair brings evolution to tire repair. Easy ...,@rexpair,https://yt3.ggpht.com/ytc/AIdro_mo3h5ArO9cGpWH...,681,0,0,UUVNFzYxySA5UFvAi32vD0cg,"bgwFR8mB7vM,ccrkFdmeQWA,J7yjvG3ShB0,MJ3FRREovh..."
15828,Cher Lloyd,UC3hhq3Twc_jTYWzfL5BCa1A,1156418780,"Music, Pop music, Electronic music",GB,NaN,3250000,2010-12-03T11:19:40Z,GREEN LIGHT - Out Now 💚 Listen here: https://l...,@thecherlloydchannel,https://yt3.ggpht.com/8ULlM9qfcLPH3CQFyOJBK9J6...,82,0,0,UU3hhq3Twc_jTYWzfL5BCa1A,"mx10eKtwq9I,f6wg0bsZDpY,nFX1wdMgApc,ybxm5RX755..."
15829,Paritosh Shorts,UCAt0ZufG7-TvfgbwkCbKd3Q,724470959,Entertainment,IN,NaN,2880000,2022-08-08T12:07:15.139731Z,"Hello Guys I’m Paritosh, दिल्ली Ka Content Cre...",@paritoshshorts,https://yt3.ggpht.com/BKye01LNtsTpU0zLrL-jRYKL...,639,0,0,UUAt0ZufG7-TvfgbwkCbKd3Q,"cj-hHGI_xqs,QcDGHvfOMeo,-iuMCj7uQ34,MDUhJFX-cH..."

In [16]:
type(data2)

pandas.DataFrame

## DataFrame ---> Combination of Multiple Series(Column)

## squeeze ---> squeeze parameter makes sure that the data is in series format

In [17]:
df = pd.read_csv('youtube_channel_info_v1.csv').squeeze('columns')
df

0                       BLACKPINK
1                     HYBE LABELS
2                   BILLIE EILISH
3                        Shemaroo
4                     JuegaGerman
                   ...
15825     Benchmark Entertainment
15826    South China Morning Post
15827                     reXpair
15828                  Cher Lloyd
15829             Paritosh Shorts
Name: channel_name, Length: 15830, dtype: str

In [18]:
type(df)

pandas.Series

In [19]:
dataframe = pd.read_csv('youtube_channel_info_v1two_column.csv',index_col = 'channel_name').squeeze('columns')
dataframe

channel_name
BLACKPINK                           99000000
HYBE LABELS                         78700000
BILLIE EILISH                          82300
Shemaroo                            60400000
JuegaGerman                         54200000
                                  ...
Benchmark Entertainment          21131599035
South China Morning Post    subscriber_count
reXpair                          21133011822
Cher Lloyd                       21134424608
Paritosh Shorts                  21135837394
Name: subscriber_count, Length: 15830, dtype: str

In [20]:
type(df)

pandas.Series

### index_col

In [21]:
pd.read_csv('youtube_channel_info_v1.csv',index_col='channel_name').squeeze('columns')

Empty DataFrame
Columns: []
Index: [BLACKPINK, HYBE LABELS, BILLIE EILISH, Shemaroo, JuegaGerman, LooLoo Kids - Nursery Rhymes and Children's Songs, Tips Official, MrBeast, El Reino Infantil, Justin Bieber, SET India, Wave Music, Colors TV, Sony Music India, Ed Sheeran, Zee TV, ChuChu TV Nursery Rhymes & Kids Songs, Ariana Grande, 5-Minute Crafts, Aaj Tak, Billion Surprise Toys, EminemMusic, Movieclips, Vlad and Niki, Sony SAB, Infobells - Hindi, Like Nastya, Taylor Swift, YRF, WWE, PewDiePie, BANGTANTV, Cocomelon - Nursery Rhymes, Jkk Entertainment, Sony PAL, Mikecrack, WorkpointOfficial, ARY Digital HD, JioHotstar Kids, Maroon 5, Badabun, YouTube, whinderssonnunes, GR6 EXPLODE, ABP NEWS, Rihanna, Kimberly Loaiza, Shakira, Bad Bunny, Daddy Yankee, Fernanfloo, ABS-CBN Entertainment, Ishtar Music, Like Nastya ESP, TEDx Talks, Felipe Neto, SonyMusicIndiaVEVO, TheEllenShow, Katy Perry, Super Simple Songs - Kids Songs, Ultra Bollywood, elrubiusOMG, Toys and Colors, One Direction, HAR PAL GEO, PowerKids TV, Alan Walker, shfa, Luisito Comunica, Masha and The Bear, XXXTENTACION, BRIGHT SIDE, Bruno Mars, CarryMinati, SSSniperWolf, Mr Bean, ImagineDragons, KHANDESHI MOVIES, YOLO AVENTURAS, Rajshri, The Weeknd, rezendeevil, Ozuna, Markiplier, NoCopyrightSounds, VEGETTA777, T-Series Bollywood Classics, SMTOWN, Ryan's World, Eros Now Music, J Balvin, MR. INDIAN HACKER, Worldwide Records Bhojpuri, Round2hell, KAROL G, Selena Gomez, Jess No Limit, DREAM, Total Gaming, MrBeast Gaming, ...]

[15830 rows x 0 columns]

## Attribute in Series

## 1. .values --- > representing only the values of the given series

In [22]:
df.values # channels and viewcounts are stored in a 2D array

<ArrowStringArray>
[                                        'BLACKPINK',
                                       'HYBE LABELS',
                                     'BILLIE EILISH',
                                          'Shemaroo',
                                       'JuegaGerman',
 'LooLoo Kids - Nursery Rhymes and Children's Songs',
                                     'Tips Official',
                                           'MrBeast',
                                 'El Reino Infantil',
                                     'Justin Bieber',
 ...
                                 '이지금 [IU Official]',
                                     'New Rockstars',
                                          'KingBach',
                                        'Link Up TV',
                                        'HNBMEDIAtv',
                           'Benchmark Entertainment',
                          'South China Morning Post',
                                           'reXpair',
                                        'Cher Lloyd',
                                   'Paritosh Shorts']
Length: 15830, dtype: str

In [23]:
dataframe.values

<ArrowStringArray>
[        '99000000',         '78700000',            '82300',
         '60400000',         '54200000',         '61000000',
         '79100000',        '443000000',         '70200000',
         '76300000',
 ...
      '21124535104',      '21125947890',      '21127360676',
      '21128773463',      '21130186249',      '21131599035',
 'subscriber_count',      '21133011822',      '21134424608',
      '21135837394']
Length: 15830, dtype: str

## 2. .index --- > returns only the index values from the given column

In [24]:
df.index # no such value

RangeIndex(start=0, stop=15830, step=1)

In [25]:
dataframe.index

Index(['BLACKPINK', 'HYBE LABELS', 'BILLIE EILISH', 'Shemaroo', 'JuegaGerman',
       'LooLoo Kids - Nursery Rhymes and Children's Songs', 'Tips Official',
       'MrBeast', 'El Reino Infantil', 'Justin Bieber',
       ...
       '이지금 [IU Official]', 'New Rockstars', 'KingBach', 'Link Up TV',
       'HNBMEDIAtv', 'Benchmark Entertainment', 'South China Morning Post',
       'reXpair', 'Cher Lloyd', 'Paritosh Shorts'],
      dtype='str', name='channel_name', length=15830)

## 3. dtype ---> Dtype Provides the idea about the data type of the values that you are storing

In [26]:
dataframe.dtype

## 4. size ---> this size attribute provides the idea about the total number of rows inside the dataset

In [27]:
dataframe.size

15830

## 5. shape ---> provides the idea about the row, column information

In [28]:
dataframe.shape

(15830,)

In [29]:
df.shape

(15830,)

In [30]:
data2.shape

(15830, 16)

## 6. ndim ---> this attribute provides the idea about the dimension of the given dataset

In [31]:
dataframe.ndim

1

In [32]:
data2.ndim

2

## 7. name ---> this attribute provides the idea about the name of the series

In [33]:
dataframe.name

'subscriber_count'

## 8. is_unique ---> checks that the unique values are there or not inside the column

In [34]:
dataframe

channel_name
BLACKPINK                           99000000
HYBE LABELS                         78700000
BILLIE EILISH                          82300
Shemaroo                            60400000
JuegaGerman                         54200000
                                  ...
Benchmark Entertainment          21131599035
South China Morning Post    subscriber_count
reXpair                          21133011822
Cher Lloyd                       21134424608
Paritosh Shorts                  21135837394
Name: subscriber_count, Length: 15830, dtype: str

In [35]:
dataframe.is_unique

False

In [36]:
dataframe.name

'subscriber_count'

In [37]:
pd.Series([1,2,3,4,5]).is_unique

True

## Series Methods

### 1. head() ---> Provides the top preview of data as the top 5 rows of the dataframe or Series

--> quite helpful with providing custom preview of the dataset

In [38]:
dataframe.head(10)

channel_name
BLACKPINK                                             99000000
HYBE LABELS                                           78700000
BILLIE EILISH                                            82300
Shemaroo                                              60400000
JuegaGerman                                           54200000
LooLoo Kids - Nursery Rhymes and Children's Songs     61000000
Tips Official                                         79100000
MrBeast                                              443000000
El Reino Infantil                                     70200000
Justin Bieber                                         76300000
Name: subscriber_count, dtype: str

In [39]:
df.head(5)

0        BLACKPINK
1      HYBE LABELS
2    BILLIE EILISH
3         Shemaroo
4      JuegaGerman
Name: channel_name, dtype: str

#### 2. tail() ---. provide the bottom preview of the data as the Bottom rows

In [40]:
dataframe.tail(5)

channel_name
Benchmark Entertainment          21131599035
South China Morning Post    subscriber_count
reXpair                          21133011822
Cher Lloyd                       21134424608
Paritosh Shorts                  21135837394
Name: subscriber_count, dtype: str

### 3. sample() ---. it provides the any custom row from the dataset for us to the preview it

### randomly

In [41]:
dataframe.sample()

channel_name
Chef Raphael    12913420991
Name: subscriber_count, dtype: str

In [42]:
dataframe.sample(5)

channel_name
WE tv                  14596049503
Berk Tanman            12459916581
Rihanna                148896558.2
G-Eazy                 16527328407
Harpreet SDC Shorts     3613048624
Name: subscriber_count, dtype: str

### 4. value_counts()

### --> it provides idea about the count of the values (categorical values)

In [43]:
data = pd.read_csv('youtube_channel_info_v2.csv',index_col = 'channel_name').squeeze('columns')

In [44]:
data

,channel_id,view_count,category,country,defaultLanguage,subscriber_count,created_date,description,custom_url,thumbnail,video_count,videos_last_30_days,views_last_30_days,uploads_playlist_id,last_10_video_ids
channel_name,,,,,,,,,,,,,,,
BLACKPINK,UCOmHUn--16B90oW2L6FRR3A,39962585446,"Music of Asia, Pop music, Music, Electronic music",KR,NaN,99000000,2016-06-29T03:15:23Z,BLACKPINK Official YouTube Channel 블랙핑크 공식 유튜브...,@blackpink,https://yt3.ggpht.com/U3VrCkKjzTpQ3VYv4SCPjNfD...,636,1,3256869,UUOmHUn--16B90oW2L6FRR3A,"W-9-keHNwV8,pAeqY-TEZc0,WB_AOdAEuBM,zTnAvaoHR4..."
HYBE LABELS,UC3IZKseVpdzPSBaWxBxundA,41604896923,"Hip hop music, Pop music, Music, Music of Asia",KR,NaN,78700000,2008-06-04T08:23:22Z,Welcome to the official YouTube channel of HYB...,@hybelabels,https://yt3.ggpht.com/ytc/AIdro_l8g0yRFG8xoe_q...,2817,79,46074833,UU3IZKseVpdzPSBaWxBxundA,"NPqiynCpqgI,nbOuR-KYZy8,xf8N3JYEhV4,iIWKCYP2zY..."
BILLIE EILISH,UCVNE660NcgYzi18LwwUZb7Q,14316364,NaN,NaN,NaN,82300,2019-01-18T05:14:32Z,NaN,@billieeilish8477,https://yt3.ggpht.com/ytc/AIdro_n3NfvUAVtcUJvW...,1,0,0,UUVNE660NcgYzi18LwwUZb7Q,C9odQay_d6s
Shemaroo,UCF1JIbMUs6uqoZEY1Haw0GQ,27011004224,"Entertainment, Film",IN,NaN,60400000,2007-09-01T11:44:51Z,"Welcome to ShemarooEnt, one of the finest dest...",@shemaroo,https://yt3.ggpht.com/ytc/AIdro_mhdF4RNZM9OHP-...,13374,63,10560897,UUF1JIbMUs6uqoZEY1Haw0GQ,"KPYx-APpvo4,HscCQYIX4fg,TP64Sacd5Nw,G8a5vnD2A0..."
JuegaGerman,UCYiGq8XF7YQD00x7wAd62Zg,17573028501,"Role-playing video game, Action game, Video ga...",CL,NaN,54200000,2013-05-19T00:09:13Z,Lento pero seguro.,@juegagerman,https://yt3.ggpht.com/vOsrLzWD4z1dbr470nEXydi3...,2368,12,22980501,UUYiGq8XF7YQD00x7wAd62Zg,"JjWksJW1Z0M,_NhOyRPXA5s,EYXTxxjU0Ks,5eAyv6b84p..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Benchmark Entertainment,UCqsXkde84Zt4pp0NbYiWe_Q,79289853,"Hip hop music, Music, Music of Asia, Pop music...",IN,NaN,241000,2020-06-07T08:21:45.961094Z,"“Benchmark Entertainment, founded in the year ...",@benchmarkentertainment,https://yt3.ggpht.com/XGtEIDLXS8HO4wkrHZkLYtQ9...,43,0,0,UUqsXkde84Zt4pp0NbYiWe_Q,"mjyaQOuqUGc,VTPA_AjHZMA,IfJL_u-gnio,5AJFf9eqJZ..."
South China Morning Post,UC4SUWizzKc1tptprBkWjX2Q,4484864729,"Society, Politics",HK,NaN,4260000,2007-01-18T08:00:37Z,"Videos from Hong Kong, Greater China and beyon...",@southchinamorningpost,https://yt3.ggpht.com/4Q9yos_fKmzf0o36ETS4IZel...,19781,124,8120594,UU4SUWizzKc1tptprBkWjX2Q,"zSX826Tfkwo,fkKvagzbFRA,kHmmcpVPSUE,fFz5HWu0yh..."
reXpair,UCVNFzYxySA5UFvAi32vD0cg,2581715060,"Vehicle, Lifestyle (sociology)",US,NaN,2920000,2021-01-26T16:11:39.950855Z,reXpair brings evolution to tire repair. Easy ...,@rexpair,https://yt3.ggpht.com/ytc/AIdro_mo3h5ArO9cGpWH...,681,0,0,UUVNFzYxySA5UFvAi32vD0cg,"bgwFR8mB7vM,ccrkFdmeQWA,J7yjvG3ShB0,MJ3FRREovh..."
Cher Lloyd,UC3hhq3Twc_jTYWzfL5BCa1A,1156418780,"Music, Pop music, Electronic music",GB,NaN,3250000,2010-12-03T11:19:40Z,GREEN LIGHT - Out Now 💚 Listen here: https://l...,@thecherlloydchannel,https://yt3.ggpht.com/8ULlM9qfcLPH3CQFyOJBK9J6...,82,0,0,UU3hhq3Twc_jTYWzfL5BCa1A,"mx10eKtwq9I,f6wg0bsZDpY,nFX1wdMgApc,ybxm5RX755..."
Paritosh Shorts,UCAt0ZufG7-TvfgbwkCbKd3Q,724470959,Entertainment,IN,NaN,2880000,2022-08-08T12:07:15.139731Z,"Hello Guys I’m Paritosh, दिल्ली Ka Content Cre...",@paritoshshorts,https://yt3.ggpht.com/BKye01LNtsTpU0zLrL-jRYKL...,639,0,0,UUAt0ZufG7-TvfgbwkCbKd3Q,"cj-hHGI_xqs,QcDGHvfOMeo,-iuMCj7uQ34,MDUhJFX-cH..."

In [45]:
yt = data['subscriber_count']
yt

channel_name
BLACKPINK                   99000000
HYBE LABELS                 78700000
BILLIE EILISH                  82300
Shemaroo                    60400000
JuegaGerman                 54200000
                              ...
Benchmark Entertainment       241000
South China Morning Post     4260000
reXpair                      2920000
Cher Lloyd                   3250000
Paritosh Shorts              2880000
Name: subscriber_count, Length: 15830, dtype: int64

In [46]:
type(yt)

pandas.Series

In [47]:
yt.value_counts()

subscriber_count
1010000    46
1070000    41
1090000    40
1030000    40
1340000    39
           ..
52200       1
66400       1
9050000     1
9440000     1
72000       1
Name: count, Length: 2530, dtype: int64

In [48]:
yt_updated = yt.head(20)
yt_updated

channel_name
BLACKPINK                                             99000000
HYBE LABELS                                           78700000
BILLIE EILISH                                            82300
Shemaroo                                              60400000
JuegaGerman                                           54200000
LooLoo Kids - Nursery Rhymes and Children's Songs     61000000
Tips Official                                         79100000
MrBeast                                              443000000
El Reino Infantil                                     70200000
Justin Bieber                                         76300000
SET India                                            187000000
Wave Music                                            67700000
Colors TV                                             81300000
Sony Music India                                      68300000
Ed Sheeran                                            58500000
Zee TV                                                95100000
ChuChu TV Nursery Rhymes & Kids Songs                 97600000
Ariana Grande                                         56500000
5-Minute Crafts                                       81000000
Aaj Tak                                               73700000
Name: subscriber_count, dtype: int64

In [49]:
yt_updated.value_counts()

subscriber_count
99000000     1
78700000     1
82300        1
60400000     1
54200000     1
61000000     1
79100000     1
443000000    1
70200000     1
76300000     1
187000000    1
67700000     1
81300000     1
68300000     1
58500000     1
95100000     1
97600000     1
56500000     1
81000000     1
73700000     1
Name: count, dtype: int64

### 5. sort_values() ---. this method sorts the values in a ascending manner, iit can be useful for us for numerical columns

### ---> you can even sort the values in the descending manner

ascending order

In [50]:
yt_updated.sort_values()

channel_name
BILLIE EILISH                                            82300
JuegaGerman                                           54200000
Ariana Grande                                         56500000
Ed Sheeran                                            58500000
Shemaroo                                              60400000
LooLoo Kids - Nursery Rhymes and Children's Songs     61000000
Wave Music                                            67700000
Sony Music India                                      68300000
El Reino Infantil                                     70200000
Aaj Tak                                               73700000
Justin Bieber                                         76300000
HYBE LABELS                                           78700000
Tips Official                                         79100000
5-Minute Crafts                                       81000000
Colors TV                                             81300000
Zee TV                                                95100000
ChuChu TV Nursery Rhymes & Kids Songs                 97600000
BLACKPINK                                             99000000
SET India                                            187000000
MrBeast                                              443000000
Name: subscriber_count, dtype: int64

descending order

In [51]:
yt_updated.sort_values(ascending = False)

channel_name
MrBeast                                              443000000
SET India                                            187000000
BLACKPINK                                             99000000
ChuChu TV Nursery Rhymes & Kids Songs                 97600000
Zee TV                                                95100000
Colors TV                                             81300000
5-Minute Crafts                                       81000000
Tips Official                                         79100000
HYBE LABELS                                           78700000
Justin Bieber                                         76300000
Aaj Tak                                               73700000
El Reino Infantil                                     70200000
Sony Music India                                      68300000
Wave Music                                            67700000
LooLoo Kids - Nursery Rhymes and Children's Songs     61000000
Shemaroo                                              60400000
Ed Sheeran                                            58500000
Ariana Grande                                         56500000
JuegaGerman                                           54200000
BILLIE EILISH                                            82300
Name: subscriber_count, dtype: int64

### 6. sort_index()

In [52]:
yt_updated.sort_index()

channel_name
5-Minute Crafts                                       81000000
Aaj Tak                                               73700000
Ariana Grande                                         56500000
BILLIE EILISH                                            82300
BLACKPINK                                             99000000
ChuChu TV Nursery Rhymes & Kids Songs                 97600000
Colors TV                                             81300000
Ed Sheeran                                            58500000
El Reino Infantil                                     70200000
HYBE LABELS                                           78700000
JuegaGerman                                           54200000
Justin Bieber                                         76300000
LooLoo Kids - Nursery Rhymes and Children's Songs     61000000
MrBeast                                              443000000
SET India                                            187000000
Shemaroo                                              60400000
Sony Music India                                      68300000
Tips Official                                         79100000
Wave Music                                            67700000
Zee TV                                                95100000
Name: subscriber_count, dtype: int64

## Method Chaining

### ---> We will use multiple methods to get the required value in a way the first method's output will be the second method's input then 2nd method output will be 3rd method's input

In [53]:
yt_updated.sort_values(ascending = False).head(1)

channel_name
MrBeast    443000000
Name: subscriber_count, dtype: int64

In [54]:
yt_updated.sort_values(ascending = False).head(1).values[0]

np.int64(443000000)

In [55]:
yt_updated

channel_name
BLACKPINK                                             99000000
HYBE LABELS                                           78700000
BILLIE EILISH                                            82300
Shemaroo                                              60400000
JuegaGerman                                           54200000
LooLoo Kids - Nursery Rhymes and Children's Songs     61000000
Tips Official                                         79100000
MrBeast                                              443000000
El Reino Infantil                                     70200000
Justin Bieber                                         76300000
SET India                                            187000000
Wave Music                                            67700000
Colors TV                                             81300000
Sony Music India                                      68300000
Ed Sheeran                                            58500000
Zee TV                                                95100000
ChuChu TV Nursery Rhymes & Kids Songs                 97600000
Ariana Grande                                         56500000
5-Minute Crafts                                       81000000
Aaj Tak                                               73700000
Name: subscriber_count, dtype: int64

In [56]:
yt_updated.sort_values()

channel_name
BILLIE EILISH                                            82300
JuegaGerman                                           54200000
Ariana Grande                                         56500000
Ed Sheeran                                            58500000
Shemaroo                                              60400000
LooLoo Kids - Nursery Rhymes and Children's Songs     61000000
Wave Music                                            67700000
Sony Music India                                      68300000
El Reino Infantil                                     70200000
Aaj Tak                                               73700000
Justin Bieber                                         76300000
HYBE LABELS                                           78700000
Tips Official                                         79100000
5-Minute Crafts                                       81000000
Colors TV                                             81300000
Zee TV                                                95100000
ChuChu TV Nursery Rhymes & Kids Songs                 97600000
BLACKPINK                                             99000000
SET India                                            187000000
MrBeast                                              443000000
Name: subscriber_count, dtype: int64

## again if we print yt_updated it will be not sorted

In [57]:
yt_updated

channel_name
BLACKPINK                                             99000000
HYBE LABELS                                           78700000
BILLIE EILISH                                            82300
Shemaroo                                              60400000
JuegaGerman                                           54200000
LooLoo Kids - Nursery Rhymes and Children's Songs     61000000
Tips Official                                         79100000
MrBeast                                              443000000
El Reino Infantil                                     70200000
Justin Bieber                                         76300000
SET India                                            187000000
Wave Music                                            67700000
Colors TV                                             81300000
Sony Music India                                      68300000
Ed Sheeran                                            58500000
Zee TV                                                95100000
ChuChu TV Nursery Rhymes & Kids Songs                 97600000
Ariana Grande                                         56500000
5-Minute Crafts                                       81000000
Aaj Tak                                               73700000
Name: subscriber_count, dtype: int64

## to make the changes permanent then use inplace keyword

In [58]:
yt_updated = yt_updated.copy()

In [59]:
yt_updated

channel_name
BLACKPINK                                             99000000
HYBE LABELS                                           78700000
BILLIE EILISH                                            82300
Shemaroo                                              60400000
JuegaGerman                                           54200000
LooLoo Kids - Nursery Rhymes and Children's Songs     61000000
Tips Official                                         79100000
MrBeast                                              443000000
El Reino Infantil                                     70200000
Justin Bieber                                         76300000
SET India                                            187000000
Wave Music                                            67700000
Colors TV                                             81300000
Sony Music India                                      68300000
Ed Sheeran                                            58500000
Zee TV                                                95100000
ChuChu TV Nursery Rhymes & Kids Songs                 97600000
Ariana Grande                                         56500000
5-Minute Crafts                                       81000000
Aaj Tak                                               73700000
Name: subscriber_count, dtype: int64

In [60]:
yt_updated.sort_values(inplace = True)

### changes coming out to be permanent

In [61]:
yt_updated

channel_name
BILLIE EILISH                                            82300
JuegaGerman                                           54200000
Ariana Grande                                         56500000
Ed Sheeran                                            58500000
Shemaroo                                              60400000
LooLoo Kids - Nursery Rhymes and Children's Songs     61000000
Wave Music                                            67700000
Sony Music India                                      68300000
El Reino Infantil                                     70200000
Aaj Tak                                               73700000
Justin Bieber                                         76300000
HYBE LABELS                                           78700000
Tips Official                                         79100000
5-Minute Crafts                                       81000000
Colors TV                                             81300000
Zee TV                                                95100000
ChuChu TV Nursery Rhymes & Kids Songs                 97600000
BLACKPINK                                             99000000
SET India                                            187000000
MrBeast                                              443000000
Name: subscriber_count, dtype: int64

In [62]:
youtube = data

In [63]:
youtube

,channel_id,view_count,category,country,defaultLanguage,subscriber_count,created_date,description,custom_url,thumbnail,video_count,videos_last_30_days,views_last_30_days,uploads_playlist_id,last_10_video_ids
channel_name,,,,,,,,,,,,,,,
BLACKPINK,UCOmHUn--16B90oW2L6FRR3A,39962585446,"Music of Asia, Pop music, Music, Electronic music",KR,NaN,99000000,2016-06-29T03:15:23Z,BLACKPINK Official YouTube Channel 블랙핑크 공식 유튜브...,@blackpink,https://yt3.ggpht.com/U3VrCkKjzTpQ3VYv4SCPjNfD...,636,1,3256869,UUOmHUn--16B90oW2L6FRR3A,"W-9-keHNwV8,pAeqY-TEZc0,WB_AOdAEuBM,zTnAvaoHR4..."
HYBE LABELS,UC3IZKseVpdzPSBaWxBxundA,41604896923,"Hip hop music, Pop music, Music, Music of Asia",KR,NaN,78700000,2008-06-04T08:23:22Z,Welcome to the official YouTube channel of HYB...,@hybelabels,https://yt3.ggpht.com/ytc/AIdro_l8g0yRFG8xoe_q...,2817,79,46074833,UU3IZKseVpdzPSBaWxBxundA,"NPqiynCpqgI,nbOuR-KYZy8,xf8N3JYEhV4,iIWKCYP2zY..."
BILLIE EILISH,UCVNE660NcgYzi18LwwUZb7Q,14316364,NaN,NaN,NaN,82300,2019-01-18T05:14:32Z,NaN,@billieeilish8477,https://yt3.ggpht.com/ytc/AIdro_n3NfvUAVtcUJvW...,1,0,0,UUVNE660NcgYzi18LwwUZb7Q,C9odQay_d6s
Shemaroo,UCF1JIbMUs6uqoZEY1Haw0GQ,27011004224,"Entertainment, Film",IN,NaN,60400000,2007-09-01T11:44:51Z,"Welcome to ShemarooEnt, one of the finest dest...",@shemaroo,https://yt3.ggpht.com/ytc/AIdro_mhdF4RNZM9OHP-...,13374,63,10560897,UUF1JIbMUs6uqoZEY1Haw0GQ,"KPYx-APpvo4,HscCQYIX4fg,TP64Sacd5Nw,G8a5vnD2A0..."
JuegaGerman,UCYiGq8XF7YQD00x7wAd62Zg,17573028501,"Role-playing video game, Action game, Video ga...",CL,NaN,54200000,2013-05-19T00:09:13Z,Lento pero seguro.,@juegagerman,https://yt3.ggpht.com/vOsrLzWD4z1dbr470nEXydi3...,2368,12,22980501,UUYiGq8XF7YQD00x7wAd62Zg,"JjWksJW1Z0M,_NhOyRPXA5s,EYXTxxjU0Ks,5eAyv6b84p..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Benchmark Entertainment,UCqsXkde84Zt4pp0NbYiWe_Q,79289853,"Hip hop music, Music, Music of Asia, Pop music...",IN,NaN,241000,2020-06-07T08:21:45.961094Z,"“Benchmark Entertainment, founded in the year ...",@benchmarkentertainment,https://yt3.ggpht.com/XGtEIDLXS8HO4wkrHZkLYtQ9...,43,0,0,UUqsXkde84Zt4pp0NbYiWe_Q,"mjyaQOuqUGc,VTPA_AjHZMA,IfJL_u-gnio,5AJFf9eqJZ..."
South China Morning Post,UC4SUWizzKc1tptprBkWjX2Q,4484864729,"Society, Politics",HK,NaN,4260000,2007-01-18T08:00:37Z,"Videos from Hong Kong, Greater China and beyon...",@southchinamorningpost,https://yt3.ggpht.com/4Q9yos_fKmzf0o36ETS4IZel...,19781,124,8120594,UU4SUWizzKc1tptprBkWjX2Q,"zSX826Tfkwo,fkKvagzbFRA,kHmmcpVPSUE,fFz5HWu0yh..."
reXpair,UCVNFzYxySA5UFvAi32vD0cg,2581715060,"Vehicle, Lifestyle (sociology)",US,NaN,2920000,2021-01-26T16:11:39.950855Z,reXpair brings evolution to tire repair. Easy ...,@rexpair,https://yt3.ggpht.com/ytc/AIdro_mo3h5ArO9cGpWH...,681,0,0,UUVNFzYxySA5UFvAi32vD0cg,"bgwFR8mB7vM,ccrkFdmeQWA,J7yjvG3ShB0,MJ3FRREovh..."
Cher Lloyd,UC3hhq3Twc_jTYWzfL5BCa1A,1156418780,"Music, Pop music, Electronic music",GB,NaN,3250000,2010-12-03T11:19:40Z,GREEN LIGHT - Out Now 💚 Listen here: https://l...,@thecherlloydchannel,https://yt3.ggpht.com/8ULlM9qfcLPH3CQFyOJBK9J6...,82,0,0,UU3hhq3Twc_jTYWzfL5BCa1A,"mx10eKtwq9I,f6wg0bsZDpY,nFX1wdMgApc,ybxm5RX755..."
Paritosh Shorts,UCAt0ZufG7-TvfgbwkCbKd3Q,724470959,Entertainment,IN,NaN,2880000,2022-08-08T12:07:15.139731Z,"Hello Guys I’m Paritosh, दिल्ली Ka Content Cre...",@paritoshshorts,https://yt3.ggpht.com/BKye01LNtsTpU0zLrL-jRYKL...,639,0,0,UUAt0ZufG7-TvfgbwkCbKd3Q,"cj-hHGI_xqs,QcDGHvfOMeo,-iuMCj7uQ34,MDUhJFX-cH..."

In [64]:
subs = youtube['subscriber_count']

In [65]:
subs

channel_name
BLACKPINK                   99000000
HYBE LABELS                 78700000
BILLIE EILISH                  82300
Shemaroo                    60400000
JuegaGerman                 54200000
                              ...
Benchmark Entertainment       241000
South China Morning Post     4260000
reXpair                      2920000
Cher Lloyd                   3250000
Paritosh Shorts              2880000
Name: subscriber_count, Length: 15830, dtype: int64

# Mathematical Functions in pandas

## 1. sum() ---> sum of all values present in the series

In [66]:
subs.sum()

np.int64(63632278000)

## 2. product() --> product of all values inside the series

In [67]:
subs.product()

np.int64(0)

In [68]:
subs.sort_values()

channel_name
Kout                              50000
XElectrica                        50000
Kasodus                           50000
Singing, I learn to Speak         50000
GAME OF MEMES 🐸                   50100
                                ...
Vlad and Niki                 146000000
SET India                     187000000
Cocomelon - Nursery Rhymes    198000000
T-Series                      305000000
MrBeast                       443000000
Name: subscriber_count, Length: 15830, dtype: int64

## 3. mean() ---> meanprovides the avg values of data column

In [69]:
avg = subs.mean()
avg

np.float64(4019726.9740998107)

## 4. median() --> median also provides the idea about the average of the data, for coming up with median, we need to sort the values in ascending manner and then the middle value after sorting the data ---> median

## --> outliers can be easily handled in the median

In [70]:
subs.median()

np.float64(1570000.0)

## 5. mode ---> it provides that which value is getting repeated maximum no:of times

In [71]:
subs.mode()

0    1010000
Name: subscriber_count, dtype: int64

## 6. std() --> if we need to get the idea that how the values inside the series are distributed from the average or mean value then we can come up with the standard deviation

#### ---> 7,8,6,7,5 --->low std
#### ---> 7,13,45,67,8 ---> high std

In [72]:
subs.std()

np.float64(8937193.096528104)

## 7. variance --- > variance also provides the insight about the distribution of the data from themean value and variance is the square of the standard deviation .
#### standard_deviation =|mean - v_1| + |mean -v_2| .... /total count of values
#### variance =std ** 2|

In [73]:
data = pd.Series([1,2,3,4,5]).var()
data

np.float64(2.5)

In [74]:
data.std()

np.float64(0.0)

In [75]:
subs.var()

np.float64(79873420444629.6)

## 8. min and max

In [76]:
subs.min()

np.int64(50000)

In [77]:
subs.max()

np.int64(443000000)

## 9. describe() ---> it provides idea about the summary of the important mathematical calculations for data

#### min --- > minimum value
#### max ---- > maximum value
#### mean ---- > average value
#### std ---- > standard deviation
#### 25% ---- > 25% of the values out of my all values are less than this specific value
#### 50% ---- > 50% of the values out of all my vakues are less than this value
#### 75% ---- > 75% of the values out of my all values are less than this specific value
#### count ---- > Total number of rows in the column

#### JEE mains --- > 25% --- > my score in JEE Mains was greater than 25 % of the total applicants who applied in JEE

In [78]:
subs.describe()

count    1.583000e+04
mean     4.019727e+06
std      8.937193e+06
min      5.000000e+04
25%      4.880000e+05
50%      1.570000e+06
75%      4.300000e+06
max      4.430000e+08
Name: subscriber_count, dtype: float64

In [79]:
yt_updated.describe()

count    2.000000e+01
mean     9.443412e+07
std      8.861651e+07
min      8.230000e+04
25%      6.085000e+07
50%      7.500000e+07
75%      8.475000e+07
max      4.430000e+08
Name: subscriber_count, dtype: float64

# Indexing in the series

## Indexing in Series (To have the access over the certain value or values)

#### 1. Positive Indexing (Just like List) ---- > start from 0 to forward direction
#### 2. NO Negative Indexing
#### 3. Slicing --- > In Series we can get the certain values over a given specific range and we can do it using [initial_val:final_val +1]
#### 4. Fancy Indexing ---- > if i want the specific values from the series then we can go with fancy indexing

In [80]:
avg = pd.Series([1,2,3,4,5,6,7,8,9,10], index = [1,2,3,4,5,6,7,8,9,10])

In [81]:
avg[2]

np.int64(2)

In [82]:
avg[1]

np.int64(1)

## slicing

In [83]:
avg[2:10]

3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

In [84]:
avg[2:10:2]

3    3
5    5
7    7
9    9
dtype: int64

In [85]:
avg[::-1]

10    10
9      9
8      8
7      7
6      6
5      5
4      4
3      3
2      2
1      1
dtype: int64

In [86]:
avg[:-1]

1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

## fancy indexing

In [87]:
avg[[2,4,6]]

2    2
4    4
6    6
dtype: int64

## 5. indexing with labels

In [88]:
dataframe

channel_name
BLACKPINK                           99000000
HYBE LABELS                         78700000
BILLIE EILISH                          82300
Shemaroo                            60400000
JuegaGerman                         54200000
                                  ...
Benchmark Entertainment          21131599035
South China Morning Post    subscriber_count
reXpair                          21133011822
Cher Lloyd                       21134424608
Paritosh Shorts                  21135837394
Name: subscriber_count, Length: 15830, dtype: str

In [89]:
dataframe['BLACKPINK']

'99000000'

In [90]:
type(dataframe['BLACKPINK'])

str

## Editing Series (Bring the changes into the values stored inside the Series)

### 1. Using Indexing --- > df[0]=65 --- > changing the original value at index 0 to 65

In [91]:
dataframe['Shemaroo']='100'

In [92]:
dataframe

channel_name
BLACKPINK                           99000000
HYBE LABELS                         78700000
BILLIE EILISH                          82300
Shemaroo                                 100
JuegaGerman                         54200000
                                  ...
Benchmark Entertainment          21131599035
South China Morning Post    subscriber_count
reXpair                          21133011822
Cher Lloyd                       21134424608
Paritosh Shorts                  21135837394
Name: subscriber_count, Length: 15830, dtype: str

## If indexing doesn't exits

In [93]:
dataframe['SaileshVlogs']='2000'

In [94]:
dataframe['SaileshVlogs'] # added

'2000'

## 2. editing for slicing in the series

In [95]:
avg

1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

In [96]:
avg[2:8] = 0

In [97]:
avg

1      1
2      2
3      0
4      0
5      0
6      0
7      0
8      0
9      9
10    10
dtype: int64

## 3. editing of the series in the fancy indexing

In [98]:
avg[[2,4,6]]=6

In [99]:
avg

1      1
2      6
3      0
4      6
5      0
6      6
7      0
8      0
9      9
10    10
dtype: int64

In [100]:
avg[[1,2,3]] = [25,26,27]

In [101]:
avg

1     25
2     26
3     27
4      6
5      0
6      6
7      0
8      0
9      9
10    10
dtype: int64

## 4. editing with Index Labelling

In [102]:
dataframe

channel_name
BLACKPINK                           99000000
HYBE LABELS                         78700000
BILLIE EILISH                          82300
Shemaroo                                 100
JuegaGerman                         54200000
                                  ...
South China Morning Post    subscriber_count
reXpair                          21133011822
Cher Lloyd                       21134424608
Paritosh Shorts                  21135837394
SaileshVlogs                            2000
Name: subscriber_count, Length: 15831, dtype: str

In [103]:
dataframe[['BLACKPINK','Shemaroo']] = ['1000','2000']

In [104]:
dataframe

channel_name
BLACKPINK                               1000
HYBE LABELS                         78700000
BILLIE EILISH                          82300
Shemaroo                                2000
JuegaGerman                         54200000
                                  ...
South China Morning Post    subscriber_count
reXpair                          21133011822
Cher Lloyd                       21134424608
Paritosh Shorts                  21135837394
SaileshVlogs                            2000
Name: subscriber_count, Length: 15831, dtype: str